window.RENEWALS_DATA = [
  {
    "account": "Renewal [2026] - CIRA (Canadian Internet Registration Authority)-",
    "owner": "Lakshay",
    "region": "AMER",
    "segment": "Renewal",
    "quarter": "Q2 2026",
    "month": "Apr",
    "closeDate": "2026-04-01",
    "status": "close-won",
    "closeLostReason": "",
    "closeLostNote": "",
    "closedWonNote": "CW, Non Profit Opportunity ( 101 -> 160 )",
    "trendTags": [],
    "icarr": -17160.0,
    "seats": 59,
    "totalCarr": 36360.0,
    "currentSeats": 160
  },
  {
    "account": "Renewal [2026] - Columbia Road-",
    "owner": "Ebel",
    "region": "EMEA",
    "segment": "Renewal",
    "quarter": "Q2 2026",
    "month": "Apr",
    "closeDate": "2026-04-01",
    "status": "close-lost",
    "closeLostReason": "Did not recognize full value",
    "closeLostNote": "SaaS budget for the year and do not see full value",
    "closedWonNote": "",
    "trendTags": [
      "budget-pricing"
    ],
    "icarr": -33600.0,
    "seats": -70,
    "totalCarr": 33600.0,
    "currentSeats": 1
  },
  {
    "account": "Renewal [2026] - Culture AI-",
    "owner": "Ebel",
    "region": "EMEA",
    "segment": "Renewal",
    "quarter": "Q2 2026",
    "month": "Apr",
    "closeDate": "2026-04-01",
    "status": "close-lost",
    "closeLostReason": "Pricing too high",
    "closeLostNote": "We only require 5-10 seats so the current package for 25-50 employees is far too expensive to maintained ENT, not interested in Business.",
    "closedWonNote": "",
    "trendTags": [
      "budget-pricing"
    ],
    "icarr": -19200.0,
    "seats": -40,
    "totalCarr": 19200.0,
    "currentSeats": 1
  },
  {
    "account": "Renewal [2026] - GHA Technologies-Velocity Land",
    "owner": "Aditya",
    "region": "AMER",
    "segment": "Renewal",
    "quarter": "Q2 2026",
    "month": "Apr",
    "closeDate": "2026-04-01",
    "status": "close-won",
    "closeLostReason": "",
    "closeLostNote": "",
    "closedWonNote": "CW Contraction (187->150)",
    "trendTags": [
      "right-sizing"
    ],
    "icarr": -17760.0,
    "seats": -37,
    "totalCarr": 89760.0,
    "currentSeats": 150
  },
  {
    "account": "Renewal [2026] - GIZEH Raucherbedarf GmbH",
    "owner": "Victor",
    "region": "EMEA",
    "segment": "Renewal",
    "quarter": "Q2 2026",
    "month": "Apr",
    "closeDate": "2026-04-01",
    "status": "close-won",
    "closeLostReason": "",
    "closeLostNote": "",
    "closedWonNote": "Expanded renewal (131+10=141). The customer is satisfied with ChatGPT and looking for extend it with their workforce and improving adoption.",
    "trendTags": [],
    "icarr": 4800.0,
    "seats": 10,
    "totalCarr": 62880.0,
    "currentSeats": 141
  },
  {
    "account": "Renewal [2026] - Herse Information Co. Ltd - ChatGPT Enterprise",
    "owner": "Ebel",
    "region": "APAC",
    "segment": "Renewal",
    "quarter": "Q2 2026",
    "month": "Apr",
    "closeDate": "2026-04-01",
    "status": "close-won",
    "closeLostReason": "",
    "closeLostNote": "",
    "closedWonNote": "Expanded renewal: 252-> 360 seats",
    "trendTags": [],
    "icarr": 51840.0,
    "seats": 108,
    "totalCarr": 172800.0,
    "currentSeats": 360
  },
  {
    "account": "Renewal [2026] - Income Research + Management-ChatGPT Enterprise",
    "owner": "Lori",
    "region": "AMER",
    "segment": "Renewal",
    "quarter": "Q2 2026",
    "month": "Apr",
    "closeDate": "2026-04-01",
    "status": "close-won",
    "closeLostReason": "",
    "closeLostNote": "",
    "closedWonNote": "Flat renewal - 83 seats -> 83 seats -> intention to renew with current seat count - not looking to expand this term",
    "trendTags": [],
    "icarr": 0.0,
    "seats": 0,
    "totalCarr": 39840.0,
    "currentSeats": 83
  },
  {
    "account": "Renewal [2026] - Lyles Services Co.-",
    "owner": "Ashana",
    "region": "AMER",
    "segment": "Renewal",
    "quarter": "Q2 2026",
    "month": "Apr",
    "closeDate": "2026-04-01",
    "status": "close-won",
    "closeLostReason": "",
    "closeLostNote": "",
    "closedWonNote": "Contraction (129 seats Entitled -> 100 seats). \"We adjusted down from 129 as we had not activated SCIM and we had old users that had departed the company that no longer needed access. We are also leveraging several AI platforms which has shifted use cases. I suspect that in the next year we will be increasing counts as more employees begin to adopt AI.\"",
    "trendTags": [
      "right-sizing",
      "org-cleanup"
    ],
    "icarr": -13920.0,
    "seats": -29,
    "totalCarr": 61920.0,
    "currentSeats": 100
  },
  {
    "account": "Renewal [2026] - Playground Tech-",
    "owner": "Ebel",
    "region": "EMEA",
    "segment": "Renewal",
    "quarter": "Q2 2026",
    "month": "Apr",
    "closeDate": "2026-04-01",
    "status": "close-lost",
    "closeLostReason": "Did not recognize full value",
    "closeLostNote": "Please check Deals note for Churn Interview questions",
    "closedWonNote": "",
    "trendTags": [],
    "icarr": -38880.0,
    "seats": -81,
    "totalCarr": 38880.0,
    "currentSeats": 1
  },
  {
    "account": "Renewal [2026] - Quantum Rise, Inc.-ChatGPT Enterprise",
    "owner": "Nicolas",
    "region": "AMER",
    "segment": "Renewal",
    "quarter": "Q2 2026",
    "month": "Apr",
    "closeDate": "2026-04-01",
    "status": "close-won",
    "closeLostReason": "",
    "closeLostNote": "",
    "closedWonNote": "Renewal/Expansion: Expanded from 25 to 36 seats. Reason: Customer was reviewing internal need close to renewal and landed above prior baseline after discussing future growth, API access, and the ability to add users later through quarterly true-up. Commercial note: 50-seat discounted pricing was explored but not retained at 36, so final scope reverted to standard $40 per seat. Positive signal: Customer actively evaluated higher seat counts and asked detailed questions on API keys, centralized provisioning, and true-up mechanics, showing broader interest in enabling more usage over time. Risk: Price sensitivity remained, especially once 50-seat discounting no longer applied, and customer continued to test cost for seats beyond 36.",
    "trendTags": [],
    "icarr": 5280.0,
    "seats": 11,
    "totalCarr": 17280.0,
    "currentSeats": 36
  },
  {
    "account": "Renewal [2026] - Stonepeak Partners",
    "owner": "Ebel",
    "region": "AMER",
    "segment": "Renewal",
    "quarter": "Q2 2026",
    "month": "Apr",
    "closeDate": "2026-04-01",
    "status": "close-won",
    "closeLostReason": "",
    "closeLostNote": "",
    "closedWonNote": "Expanded renewal: 239->250",
    "trendTags": [],
    "icarr": -720.0,
    "seats": 11,
    "totalCarr": 114000.0,
    "currentSeats": 250
  },
  {
    "account": "Renewal [2026] - Waterfall Asset Management - ChatGPT Enterprise",
    "owner": "Tyler",
    "region": "AMER",
    "segment": "Renewal",
    "quarter": "Q2 2026",
    "month": "Apr",
    "closeDate": "2026-04-01",
    "status": "close-won",
    "closeLostReason": "",
    "closeLostNote": "",
    "closedWonNote": "Flat 50 -> 50",
    "trendTags": [],
    "icarr": 0.0,
    "seats": 0,
    "totalCarr": 24000.0,
    "currentSeats": 50
  },
  {
    "account": "Renewal [2026] - Zelestra-",
    "owner": "Victor",
    "region": "EMEA",
    "segment": "Renewal",
    "quarter": "Q2 2026",
    "month": "Apr",
    "closeDate": "2026-04-01",
    "status": "close-won",
    "closeLostReason": "",
    "closeLostNote": "",
    "closedWonNote": "Expanded renewal (150+200=350), the customer wanted an expansion before the end of the renewal period finished. We have done an early renewal inside the renewal period. We had to adjust the price to win over Claude as a competitor, which they were already evaluating, within our considered margins so that we have managed a positive iCARR of $75,000. The customer values their saved projects in their Enterprise workspace and access to API together with CustomGPTs over what the product from Anthropic offers.",
    "trendTags": [],
    "icarr": 75000.0,
    "seats": 200,
    "totalCarr": 147000.0,
    "currentSeats": 350
  },
  {
    "account": "Renewal [2026] - Atomico- ChatGPT Enterprise",
    "owner": "Nicolas",
    "region": "EMEA",
    "segment": "Renewal",
    "quarter": "Q2 2026",
    "month": "Apr",
    "closeDate": "2026-04-02",
    "status": "close-won",
    "closeLostReason": "",
    "closeLostNote": "",
    "closedWonNote": "Renewal Reduction - 60 -> 25 Reason: Customer renewed 25 ChatGPT Enterprise seats after evaluating Business and alternative vendors. Decision was driven by a mix of budget, governance concerns, and stronger perceived fit elsewhere for a broader user group. Value / retained use case: Customer still sees clear value in ChatGPT for a smaller set of power users. Enterprise points that helped retain the account were pooled credits, admin controls, analytics, and flexibility to scale users later. Risk / context: Account appears to have been under-deployed. Customer had only enabled Drive and was not aware of broader connectors and Skills, which likely limited adoption before renewal.",
    "trendTags": [
      "budget-pricing"
    ],
    "icarr": -16800.0,
    "seats": -35,
    "totalCarr": 28800.0,
    "currentSeats": 25
  },
  {
    "account": "Renewal [2026] - Brighter Super-ChatGPT Enterprise",
    "owner": "Ebel",
    "region": "APAC",
    "segment": "Renewal",
    "quarter": "Q2 2026",
    "month": "Apr",
    "closeDate": "2026-04-02",
    "status": "close-won",
    "closeLostReason": "",
    "closeLostNote": "",
    "closedWonNote": "Expanded renewal: 31->40 seats.",
    "trendTags": [],
    "icarr": 4320.0,
    "seats": 9,
    "totalCarr": 14880.0,
    "currentSeats": 40
  },
  {
    "account": "Renewal [2026] - Integra Capital - Renewal",
    "owner": "Victor",
    "region": "LATAM",
    "segment": "Renewal",
    "quarter": "Q2 2026",
    "month": "Apr",
    "closeDate": "2026-04-02",
    "status": "close-won",
    "closeLostReason": "",
    "closeLostNote": "",
    "closedWonNote": "Expanded renewal (175+8=183). The customer had strong objections about not having a dedicated AD that could provide them information about their consumption. I managed to answer their questions about consumption and how the CBP works, explaining that the service has been updated for SMB. They have ended up doing an expanded renewal.",
    "trendTags": [],
    "icarr": 3840.0,
    "seats": 8,
    "totalCarr": 84000.0,
    "currentSeats": 183
  },
  {
    "account": "Renewal [2026] - IDEAYA Biosciences - Renewal",
    "owner": "Ashana",
    "region": "AMER",
    "segment": "Renewal",
    "quarter": "Q2 2026",
    "month": "Apr",
    "closeDate": "2026-04-03",
    "status": "close-won",
    "closeLostReason": "",
    "closeLostNote": "",
    "closedWonNote": "Expansion (220 Seats Entitled -> 300 seats. Customer responded to my email and expressed interest to expand to 300 seats. He also stated that if they need more seats throughout the term they will true-up.",
    "trendTags": [],
    "icarr": 38400.0,
    "seats": 80,
    "totalCarr": 105600.0,
    "currentSeats": 300
  },
  {
    "account": "Renewal [2026] - BDT & MSD - ChatGPT Enterprise",
    "owner": "Chantal",
    "region": "AMER",
    "segment": "Renewal",
    "quarter": "Q2 2026",
    "month": "Apr",
    "closeDate": "2026-04-06",
    "status": "close-won",
    "closeLostReason": "",
    "closeLostNote": "",
    "closedWonNote": "Contraction Renewal - 500 seats -> 450 seats. Company size for this term is 450 employees, roughly 200 of those are relatively light ChatGPT users, with about 100 of those rarely using it at all. \"Today we?re using a mix of tools, including ChatGPT Enterprise, Glean, Claude, Microsoft Copilot, and a few workflow?specific AI tools\"",
    "trendTags": [
      "right-sizing",
      "competitive-shift"
    ],
    "icarr": -29400.0,
    "seats": -50,
    "totalCarr": 240000.0,
    "currentSeats": 450
  },
  {
    "account": "Renewal [2026] - CLV Group - ChatGPT Enterprise",
    "owner": "Lori",
    "region": "AMER",
    "segment": "Renewal",
    "quarter": "Q2 2026",
    "month": "Apr",
    "closeDate": "2026-04-06",
    "status": "close-won",
    "closeLostReason": "",
    "closeLostNote": "",
    "closedWonNote": "Expansion renewal - 40 seats -> 41 seats -> expects expansion throughout the year, but needs to speak with his Executive team which he couldn't speak with in time before the renewal so he will be expanding throughout the year, he just wasn't sure how many.",
    "trendTags": [],
    "icarr": 480.0,
    "seats": 1,
    "totalCarr": 19200.0,
    "currentSeats": 41
  },
  {
    "account": "Renewal [2026] - HCI Equity Partners-",
    "owner": "Tyler",
    "region": "AMER",
    "segment": "Renewal",
    "quarter": "Q2 2026",
    "month": "Apr",
    "closeDate": "2026-04-06",
    "status": "close-lost",
    "closeLostReason": "Competitor",
    "closeLostNote": "Originally wanted to downsize the workspace size from 25 to 5 which is not possible with ChatGPT Enterprise. They have now decided to switch to Claude.",
    "closedWonNote": "",
    "trendTags": [
      "right-sizing",
      "competitive-shift"
    ],
    "icarr": -12000.0,
    "seats": -25,
    "totalCarr": 12000.0,
    "currentSeats": 25
  },
  {
    "account": "Renewal [2026] - Purewest Resources Inc-ChatGPT Enterprise",
    "owner": "Lori",
    "region": "AMER",
    "segment": "Renewal",
    "quarter": "Q2 2026",
    "month": "Apr",
    "closeDate": "2026-04-06",
    "status": "close-won",
    "closeLostReason": "",
    "closeLostNote": "",
    "closedWonNote": "Contraction renewal - 190 seats -> 170 seats -> over purchased seats last term.",
    "trendTags": [
      "right-sizing"
    ],
    "icarr": -9600.0,
    "seats": -20,
    "totalCarr": 91200.0,
    "currentSeats": 170
  },
  {
    "account": "Renewal [2026] - Alto Solutions Inc-ChatGPT Enterprise",
    "owner": "Ebel",
    "region": "AMER",
    "segment": "Renewal",
    "quarter": "Q2 2026",
    "month": "Apr",
    "closeDate": "2026-04-07",
    "status": "close-won",
    "closeLostReason": "",
    "closeLostNote": "",
    "closedWonNote": "Contracted Churn: 85->30 Please check deal notes.",
    "trendTags": [],
    "icarr": -26760.0,
    "seats": -55,
    "totalCarr": 40800.0,
    "currentSeats": 30
  },
  {
    "account": "Renewal [2026] - AppOmni Inc - ChatGPT Enterprise",
    "owner": "Victor",
    "region": "AMER",
    "segment": "Renewal",
    "quarter": "Q2 2026",
    "month": "Apr",
    "closeDate": "2026-04-07",
    "status": "close-won",
    "closeLostReason": "",
    "closeLostNote": "",
    "closedWonNote": "Contracted renewal (175-75=100). The engineers in the company are trying Claude. I explained the advantages of ChatGPT Enterprise for all their kind of users and consistency, but the decision to reduce Enterprise to 100 was already taken.",
    "trendTags": [
      "right-sizing",
      "competitive-shift"
    ],
    "icarr": -36000.0,
    "seats": -75,
    "totalCarr": 84000.0,
    "currentSeats": 100
  },
  {
    "account": "Renewal [2026] - InterRent-New Business",
    "owner": "Victor",
    "region": "AMER",
    "segment": "Renewal",
    "quarter": "Q2 2026",
    "month": "Apr",
    "closeDate": "2026-04-07",
    "status": "close-won",
    "closeLostReason": "",
    "closeLostNote": "",
    "closedWonNote": "Contracted renewal (117-6=111). The customer wanted to renew but they have slightly reduce the number of users because of business reasons.",
    "trendTags": [
      "right-sizing"
    ],
    "icarr": -1920.0,
    "seats": -4,
    "totalCarr": 53280.0,
    "currentSeats": 111
  },
  {
    "account": "Renewal [2026] - Javits-ChatGPT Enterprise",
    "owner": "Ashana",
    "region": "AMER",
    "segment": "Renewal",
    "quarter": "Q2 2026",
    "month": "Apr",
    "closeDate": "2026-04-07",
    "status": "close-won",
    "closeLostReason": "",
    "closeLostNote": "",
    "closedWonNote": "Expansion (32 seats entitled -> 40 seats). They increased seats being that they are slowly rolling out to more employees as they discover more use cases and benefits for particular teams.",
    "trendTags": [],
    "icarr": 3840.0,
    "seats": 8,
    "totalCarr": 15360.0,
    "currentSeats": 40
  },
  {
    "account": "Renewal [2026] - Lysa AB-",
    "owner": "Victor",
    "region": "EMEA",
    "segment": "Renewal",
    "quarter": "Q2 2026",
    "month": "Apr",
    "closeDate": "2026-04-07",
    "status": "close-won",
    "closeLostReason": "",
    "closeLostNote": "",
    "closedWonNote": "Expanded renewal (72+17=89), the customer was happy to improve their ChatGPT Enterprise adoption to all their 89 users.",
    "trendTags": [],
    "icarr": 8160.0,
    "seats": 17,
    "totalCarr": 34560.0,
    "currentSeats": 89
  },
  {
    "account": "Renewal [2026] - Redwood Trust Inc.-ChatGPT Enterprise",
    "owner": "Lakshay",
    "region": "AMER",
    "segment": "Renewal",
    "quarter": "Q2 2026",
    "month": "Apr",
    "closeDate": "2026-04-07",
    "status": "close-won",
    "closeLostReason": "",
    "closeLostNote": "",
    "closedWonNote": "CW with an expansion ( 246 -> 274 ) at $45/seat pricing",
    "trendTags": [],
    "icarr": 15660.0,
    "seats": 29,
    "totalCarr": 132840.0,
    "currentSeats": 275
  },
  {
    "account": "Renewal [2026] - The Extreme Light Infrastructure ERIC-",
    "owner": "Ebel",
    "region": "EMEA",
    "segment": "Renewal",
    "quarter": "Q2 2026",
    "month": "Apr",
    "closeDate": "2026-04-07",
    "status": "close-won",
    "closeLostReason": "",
    "closeLostNote": "",
    "closedWonNote": "Expanded renewal: 119->165 seats Non-profit price applied",
    "trendTags": [],
    "icarr": -37320.0,
    "seats": 46,
    "totalCarr": 66720.0,
    "currentSeats": 165
  },
  {
    "account": "Renewal [2026] - Admiral Pioneer - ChatGPT Enterprise",
    "owner": "Ebel",
    "region": "EMEA",
    "segment": "Renewal",
    "quarter": "Q2 2026",
    "month": "Apr",
    "closeDate": "2026-04-08",
    "status": "close-won",
    "closeLostReason": "",
    "closeLostNote": "",
    "closedWonNote": "Expanded renewal 150->175 seats",
    "trendTags": [],
    "icarr": 12000.0,
    "seats": 25,
    "totalCarr": 72000.0,
    "currentSeats": 175
  },
  {
    "account": "Renewal [2026] - Shenkman Capital Management Inc.-ChatGPT Enterprise",
    "owner": "Nicolas",
    "region": "AMER",
    "segment": "Renewal",
    "quarter": "Q2 2026",
    "month": "Apr",
    "closeDate": "2026-04-08",
    "status": "close-won",
    "closeLostReason": "",
    "closeLostNote": "",
    "closedWonNote": "Renewal Expansion - 108 -> 120 Reason: Customer initially reviewed a lower seat range but ultimately confirmed renewal at 120 seats. Small commercial push on price was resolved with approved discounting, and customer also clarified annual billing for the ChatGPT Enterprise renewal. Value / usage signal: Customer stated they are definitely renewing, was evaluating broader tool usage including Microsoft integrations, and final signer confirmed execution of the order form.",
    "trendTags": [],
    "icarr": 4320.0,
    "seats": 12,
    "totalCarr": 51840.0,
    "currentSeats": 120
  },
  {
    "account": "Renewal [2026] - TBK Automatisierung und Messtechnik GmbH-",
    "owner": "Victor",
    "region": "EMEA",
    "segment": "Renewal",
    "quarter": "Q2 2026",
    "month": "Apr",
    "closeDate": "2026-04-08",
    "status": "close-won",
    "closeLostReason": "",
    "closeLostNote": "",
    "closedWonNote": "Flat Renewal (45 seats). The customer has the same needs as last year and is satisfied with the product.",
    "trendTags": [],
    "icarr": 3780.0,
    "seats": 0,
    "totalCarr": 17820.0,
    "currentSeats": 45
  },
  {
    "account": "Renewal [2026] - ISI Enterprises - ChatGPT Enterprise",
    "owner": "Lori",
    "region": "AMER",
    "segment": "Renewal",
    "quarter": "Q2 2026",
    "month": "Apr",
    "closeDate": "2026-04-09",
    "status": "close-won",
    "closeLostReason": "",
    "closeLostNote": "",
    "closedWonNote": "Contraction renewal - 152 seats -> 75 seats -> over purchased seats last term.",
    "trendTags": [
      "right-sizing"
    ],
    "icarr": -36960.0,
    "seats": -77,
    "totalCarr": 72960.0,
    "currentSeats": 75
  },
  {
    "account": "Renewal [2026] - National Rural Utilities Cooperative Finance Corporation-ChatGPT Enterprise",
    "owner": "Ashana",
    "region": "AMER",
    "segment": "Renewal",
    "quarter": "Q2 2026",
    "month": "Apr",
    "closeDate": "2026-04-09",
    "status": "close-won",
    "closeLostReason": "",
    "closeLostNote": "",
    "closedWonNote": "Expansion (46 seats Entitled -> 51 seats). They didn't give any major reason for their expansion. They just wanted to renew with that amount.",
    "trendTags": [],
    "icarr": 2400.0,
    "seats": 5,
    "totalCarr": 22080.0,
    "currentSeats": 51
  },
  {
    "account": "Renewal [2026] - CU Direct Corporation-ChatGPT Enterprise",
    "owner": "Chantal",
    "region": "AMER",
    "segment": "Renewal",
    "quarter": "Q2 2026",
    "month": "Apr",
    "closeDate": "2026-04-10",
    "status": "close-won",
    "closeLostReason": "",
    "closeLostNote": "",
    "closedWonNote": "Expansion -> 25 -> 47",
    "trendTags": [],
    "icarr": 10560.0,
    "seats": 22,
    "totalCarr": 22560.0,
    "currentSeats": 47
  },
  {
    "account": "Renewal [2026] - CareDx Inc. // ChatGPT Enterprise",
    "owner": "Chantal",
    "region": "AMER",
    "segment": "Renewal",
    "quarter": "Q2 2026",
    "month": "Apr",
    "closeDate": "2026-04-10",
    "status": "close-won",
    "closeLostReason": "",
    "closeLostNote": "",
    "closedWonNote": "Expansion -> 88 seats -> 96 seats",
    "trendTags": [],
    "icarr": 3840.0,
    "seats": 8,
    "totalCarr": 46080.0,
    "currentSeats": 96
  },
  {
    "account": "Renewal [2026] - First Eagle Investments - ChatGPT Enterprise",
    "owner": "Chantal",
    "region": "AMER",
    "segment": "Renewal",
    "quarter": "Q2 2026",
    "month": "Apr",
    "closeDate": "2026-04-10",
    "status": "close-won",
    "closeLostReason": "",
    "closeLostNote": "",
    "closedWonNote": "Expansion -> 250 -> 290",
    "trendTags": [],
    "icarr": 19200.0,
    "seats": 40,
    "totalCarr": 120000.0,
    "currentSeats": 290
  },
  {
    "account": "Renewal [2026] - Jones & Wagener - ChatGPT Enterprise",
    "owner": "Nicolas",
    "region": "EMEA",
    "segment": "Renewal",
    "quarter": "Q2 2026",
    "month": "Apr",
    "closeDate": "2026-04-10",
    "status": "close-won",
    "closeLostReason": "",
    "closeLostNote": "",
    "closedWonNote": "Renewal Expansion - 150 -> 165 Reason: Customer confirmed renewal at 165 seats for the foreseeable future. Increase is modest and reflects steady growth rather than a broader expansion plan. Value / usage signal: Customer added about 15 users over the past year and expects total usage to stay around 165 to 170 users over the next year.",
    "trendTags": [],
    "icarr": 7200.0,
    "seats": 15,
    "totalCarr": 72000.0,
    "currentSeats": 165
  },
  {
    "account": "Renewal [2026] - Vane Brothers (ChatGPT 25)-",
    "owner": "Chantal",
    "region": "AMER",
    "segment": "Renewal",
    "quarter": "Q2 2026",
    "month": "Apr",
    "closeDate": "2026-04-10",
    "status": "close-won",
    "closeLostReason": "",
    "closeLostNote": "",
    "closedWonNote": "Flat Renewal - 25 seats -> 25 seats",
    "trendTags": [],
    "icarr": 0.0,
    "seats": 0,
    "totalCarr": 12000.0,
    "currentSeats": 25
  },
  {
    "account": "Renewal [2026] - Cydcor, LLC-ChatGPT Enterprise",
    "owner": "Nicolas",
    "region": "AMER",
    "segment": "Renewal",
    "quarter": "Q2 2026",
    "month": "Apr",
    "closeDate": "2026-04-13",
    "status": "close-won",
    "closeLostReason": "",
    "closeLostNote": "",
    "closedWonNote": "Renewal/Expansion: 153 -> 165 seats. Reason: Customer completed the ChatGPT Enterprise renewal with a modest seat increase after internal review and follow-up discussions on final seat count. Value/usage signal: Customer moved forward on renewal, engaged on flexible pricing and admin controls, and previously involved additional stakeholders in rollout/review, indicating continued active deployment and value across the team.",
    "trendTags": [],
    "icarr": 5760.0,
    "seats": 12,
    "totalCarr": 73440.0,
    "currentSeats": 165
  },
  {
    "account": "Renewal [2026] - Great Elm Group, Inc.-ChatGPT Enterprise",
    "owner": "Chantal",
    "region": "AMER",
    "segment": "Renewal",
    "quarter": "Q2 2026",
    "month": "Apr",
    "closeDate": "2026-04-13",
    "status": "close-won",
    "closeLostReason": "",
    "closeLostNote": "",
    "closedWonNote": "Flat renewal at 50 seats",
    "trendTags": [],
    "icarr": 0.0,
    "seats": 0,
    "totalCarr": 24000.0,
    "currentSeats": 50
  },
  {
    "account": "Renewal [2026] - Leave a Nest - ChatGPT 150 seats",
    "owner": "Ebel",
    "region": "APAC",
    "segment": "Renewal",
    "quarter": "Q2 2026",
    "month": "Apr",
    "closeDate": "2026-04-13",
    "status": "close-won",
    "closeLostReason": "",
    "closeLostNote": "",
    "closedWonNote": "Flat renewal: 150-> 150 seats",
    "trendTags": [],
    "icarr": 0.0,
    "seats": 0,
    "totalCarr": 72000.0,
    "currentSeats": 150
  },
  {
    "account": "Renewal [2026] - Liontrust Asset Management-ChatGPT Enterprise",
    "owner": "Aditya",
    "region": "EMEA",
    "segment": "Renewal",
    "quarter": "Q2 2026",
    "month": "Apr",
    "closeDate": "2026-04-13",
    "status": "close-won",
    "closeLostReason": "",
    "closeLostNote": "",
    "closedWonNote": "Expansion (55->55)",
    "trendTags": [],
    "icarr": 2400.0,
    "seats": 5,
    "totalCarr": 24000.0,
    "currentSeats": 55
  },
  {
    "account": "Renewal [2026] - Monobank - ChatGPT Enterprise",
    "owner": "Victor",
    "region": "EMEA",
    "segment": "Renewal",
    "quarter": "Q2 2026",
    "month": "Apr",
    "closeDate": "2026-04-13",
    "status": "close-won",
    "closeLostReason": "",
    "closeLostNote": "",
    "closedWonNote": "Contracted renewal (430-130=300). Due to internal restructuring and budget adjustment, they needed to reduce the number of active seats in this time of the year, very seemingly increasing in the future if things go as they expect, but same as they did with the contract last year, they don't want to compromise for a higher number.",
    "trendTags": [
      "right-sizing",
      "budget-pricing"
    ],
    "icarr": -62400.0,
    "seats": -130,
    "totalCarr": 144000.0,
    "currentSeats": 300
  },
  {
    "account": "Renewal [2026] - iSeatz - Renewal",
    "owner": "Lori",
    "region": "AMER",
    "segment": "Renewal",
    "quarter": "Q2 2026",
    "month": "Apr",
    "closeDate": "2026-04-13",
    "status": "close-won",
    "closeLostReason": "",
    "closeLostNote": "",
    "closedWonNote": "Contraction Renewal - 150 seats -> 120 seats - over purchased seats",
    "trendTags": [
      "right-sizing"
    ],
    "icarr": -14400.0,
    "seats": -30,
    "totalCarr": 57600.0,
    "currentSeats": 120
  },
  {
    "account": "Renewal [2026] - BioWound Solutions-ChatGPT Enterprise",
    "owner": "Aditya",
    "region": "AMER",
    "segment": "Renewal",
    "quarter": "Q2 2026",
    "month": "Apr",
    "closeDate": "2026-04-14",
    "status": "close-won",
    "closeLostReason": "",
    "closeLostNote": "",
    "closedWonNote": "Prospect initially requested a quote through Carahsoft and indicated they work with a distributor, Insight. They later followed up and agreed to proceed with a direct engagement for now. However, they noted that for next year, they would prefer to route the purchase through their distributor. CW( 25->40)",
    "trendTags": [],
    "icarr": 7200.0,
    "seats": 15,
    "totalCarr": 12000.0,
    "currentSeats": 40
  },
  {
    "account": "Renewal [2026] - Kirton McConkie-ChatGPT Enterprise",
    "owner": "Aditya",
    "region": "AMER",
    "segment": "Renewal",
    "quarter": "Q2 2026",
    "month": "Apr",
    "closeDate": "2026-04-14",
    "status": "close-won",
    "closeLostReason": "",
    "closeLostNote": "",
    "closedWonNote": "Easy Renewal, straight to the business. CW (185 -> 235)",
    "trendTags": [],
    "icarr": 24000.0,
    "seats": 50,
    "totalCarr": 88800.0,
    "currentSeats": 235
  },
  {
    "account": "Renewal [2026] - LRN- ChatGPT Enterprise",
    "owner": "Lakshay",
    "region": "",
    "segment": "Renewal",
    "quarter": "Q2 2026",
    "month": "Apr",
    "closeDate": "2026-04-14",
    "status": "close-won",
    "closeLostReason": "",
    "closeLostNote": "",
    "closedWonNote": "Closed won with Flat Renewal 200 seats, customer showed a lot of inclination to other tools and pricing and want to diversify the AI usage in the organization",
    "trendTags": [],
    "icarr": 0.0,
    "seats": 0,
    "totalCarr": 96000.0,
    "currentSeats": 200
  },
  {
    "account": "Renewal [2026] - Lucid Group Communications - ChatGPT Enterprise (CBP)",
    "owner": "Ebel",
    "region": "EMEA",
    "segment": "Renewal",
    "quarter": "Q2 2026",
    "month": "Apr",
    "closeDate": "2026-04-14",
    "status": "close-won",
    "closeLostReason": "",
    "closeLostNote": "",
    "closedWonNote": "Contracted renewal: 480->420 seats. Please check Deal Notes",
    "trendTags": [
      "right-sizing"
    ],
    "icarr": 23760.0,
    "seats": -60,
    "totalCarr": 172800.0,
    "currentSeats": 420
  },
  {
    "account": "Renewal [2026] - Prospect Administration - ChatGPT Enterprise - Land 100",
    "owner": "Lakshay",
    "region": "",
    "segment": "Renewal",
    "quarter": "Q2 2026",
    "month": "Apr",
    "closeDate": "2026-04-14",
    "status": "close-won",
    "closeLostReason": "",
    "closeLostNote": "",
    "closedWonNote": "CW with an expansion ( 106-> 111 ), showed interest in Claude and indicated strong Claude Adoption",
    "trendTags": [],
    "icarr": 1068.0,
    "seats": 5,
    "totalCarr": 51948.0,
    "currentSeats": 111
  },
  {
    "account": "Renewal [2026] - echion Corporate Communication AG-",
    "owner": "Victor",
    "region": "EMEA",
    "segment": "Renewal",
    "quarter": "Q2 2026",
    "month": "Apr",
    "closeDate": "2026-04-14",
    "status": "close-won",
    "closeLostReason": "",
    "closeLostNote": "",
    "closedWonNote": "Flat renewal (25 seats). Product solves specific needs, no variation from last year.",
    "trendTags": [],
    "icarr": 0.0,
    "seats": 0,
    "totalCarr": 12000.0,
    "currentSeats": 25
  },
  {
    "account": "Renewal [2026] - Apax Partners - ChatGPT Enterprise",
    "owner": "Victor",
    "region": "EMEA",
    "segment": "Renewal",
    "quarter": "Q2 2026",
    "month": "Apr",
    "closeDate": "2026-04-15",
    "status": "close-won",
    "closeLostReason": "",
    "closeLostNote": "",
    "closedWonNote": "Expanded renewal (324+5=329). The customer had interest in understanding the pooled credit systems and reacted positively to the option of having 600 per user/month. He also wanted to clean up some users but after being informed of Admin Tools possibilities,, group works and how RBAC works, he decided to go up until 329 seats.",
    "trendTags": [],
    "icarr": 2400.0,
    "seats": 5,
    "totalCarr": 155520.0,
    "currentSeats": 329
  },
  {
    "account": "Renewal [2026] - Day One Biopharmaceuticals-",
    "owner": "Tyler",
    "region": "AMER",
    "segment": "Renewal",
    "quarter": "Q2 2026",
    "month": "Apr",
    "closeDate": "2026-04-15",
    "status": "close-won",
    "closeLostReason": "",
    "closeLostNote": "",
    "closedWonNote": "152 -> 163 seats",
    "trendTags": [],
    "icarr": 5280.0,
    "seats": 11,
    "totalCarr": 78240.0,
    "currentSeats": 163
  },
  {
    "account": "Renewal [2026] - EUC - Chat",
    "owner": "Ebel",
    "region": "APAC",
    "segment": "Renewal",
    "quarter": "Q2 2026",
    "month": "Apr",
    "closeDate": "2026-04-15",
    "status": "close-won",
    "closeLostReason": "",
    "closeLostNote": "",
    "closedWonNote": "contracted renewal: 227->170 seats Operational cost and competitors (for automatisation)",
    "trendTags": [
      "right-sizing",
      "competitive-shift",
      "budget-pricing"
    ],
    "icarr": -13740.0,
    "seats": -57,
    "totalCarr": 45340.0,
    "currentSeats": 170
  },
  {
    "account": "Renewal [2026] - First Round - ChatGPT Enterprise",
    "owner": "Chantal",
    "region": "AMER",
    "segment": "Renewal",
    "quarter": "Q2 2026",
    "month": "Apr",
    "closeDate": "2026-04-15",
    "status": "close-won",
    "closeLostReason": "",
    "closeLostNote": "",
    "closedWonNote": "Expansion Renewal - 57 seats -> 58 seats. Wanted to renew with current activated seat count to cover all current users. \"We actually have ChatGPT rolled out to 100% of our employees so we are already at full coverage!\"",
    "trendTags": [],
    "icarr": 480.0,
    "seats": 1,
    "totalCarr": 27360.0,
    "currentSeats": 58
  },
  {
    "account": "Renewal [2026] - Heaven Hill Brands- chatgpt 400 CBP",
    "owner": "Lori",
    "region": "AMER",
    "segment": "Renewal",
    "quarter": "Q2 2026",
    "month": "Apr",
    "closeDate": "2026-04-15",
    "status": "close-won",
    "closeLostReason": "",
    "closeLostNote": "",
    "closedWonNote": "Expansion Renewal - 669 seats -> 694 seats",
    "trendTags": [],
    "icarr": 52140.0,
    "seats": 25,
    "totalCarr": 333120.0,
    "currentSeats": 694
  },
  {
    "account": "Renewal [2026] - OddBytes Inc. - ChatGPT Enterprise",
    "owner": "Lori",
    "region": "AMER",
    "segment": "Renewal",
    "quarter": "Q2 2026",
    "month": "Apr",
    "closeDate": "2026-04-15",
    "status": "close-won",
    "closeLostReason": "",
    "closeLostNote": "",
    "closedWonNote": "Expansion Renewal - 138 seats -> 140 seats -> Expanding but doesn't see growth to be that fast, however does need 2 more seats so they asked for 140. Everything went smoothly.",
    "trendTags": [],
    "icarr": 960.0,
    "seats": 2,
    "totalCarr": 66240.0,
    "currentSeats": 140
  },
  {
    "account": "Renewal [2026] - Polar Capital Partners Ltd - ChatGPT Enterprise",
    "owner": "Ebel",
    "region": "EMEA",
    "segment": "Renewal",
    "quarter": "Q2 2026",
    "month": "Apr",
    "closeDate": "2026-04-15",
    "status": "close-won",
    "closeLostReason": "",
    "closeLostNote": "",
    "closedWonNote": "Expanded renewal: 150->167 seats",
    "trendTags": [],
    "icarr": 8160.0,
    "seats": 17,
    "totalCarr": 72000.0,
    "currentSeats": 167
  },
  {
    "account": "Renewal [2026] - Davidson Technology Consulting-NB-Cbiz-100",
    "owner": "Nicolas",
    "region": "APAC",
    "segment": "Renewal",
    "quarter": "Q2 2026",
    "month": "Apr",
    "closeDate": "2026-04-16",
    "status": "close-won",
    "closeLostReason": "",
    "closeLostNote": "",
    "closedWonNote": "Flat renewal confirmed at 100 seats. Customer reviewed usage internally and chose to renew at the current 100-seat level, with no immediate expansion at renewal. They asked about pricing impact for adding 10, 20, or 30 users later, and were advised this can be handled post-renewal through the true-up process. Jacqui confirmed she is the signer, Steven Marks had left the business, and the renewal was redirected accordingly.",
    "trendTags": [],
    "icarr": 0.0,
    "seats": 0,
    "totalCarr": 48000.0,
    "currentSeats": 100
  },
  {
    "account": "Renewal [2026] - Liberty Tax Services - ChatGPT Enterprise",
    "owner": "Lakshay",
    "region": "AMER",
    "segment": "Renewal",
    "quarter": "Q2 2026",
    "month": "Apr",
    "closeDate": "2026-04-16",
    "status": "close-won",
    "closeLostReason": "",
    "closeLostNote": "",
    "closedWonNote": "CW ( 87-> 78) , They reduced the number to remove duplicate seats caused by aliases and name changes.",
    "trendTags": [
      "org-cleanup"
    ],
    "icarr": -4320.0,
    "seats": -9,
    "totalCarr": 41760.0,
    "currentSeats": 78
  },
  {
    "account": "Renewal [2026] - Prophix - ChatGPT Enterprise",
    "owner": "Tyler",
    "region": "AMER",
    "segment": "Renewal",
    "quarter": "Q2 2026",
    "month": "Apr",
    "closeDate": "2026-04-16",
    "status": "close-won",
    "closeLostReason": "",
    "closeLostNote": "",
    "closedWonNote": "317 > 100 seats. They wanted to drop down to business as they are looking to fully migrate to Claude by the end of May. I spoke with them and pushed them for one more year of enterprise with 100 seats.",
    "trendTags": [
      "competitive-shift"
    ],
    "icarr": -104160.0,
    "seats": -217,
    "totalCarr": 152160.0,
    "currentSeats": 100
  },
  {
    "account": "Renewal [2026] - VeriSign - ChatGPT Enterprise",
    "owner": "Lori",
    "region": "AMER",
    "segment": "Renewal",
    "quarter": "Q2 2026",
    "month": "Apr",
    "closeDate": "2026-04-16",
    "status": "close-won",
    "closeLostReason": "",
    "closeLostNote": "",
    "closedWonNote": "Flat Renewal - 150 seats -> 150 seats - No room for expansion at this time.",
    "trendTags": [],
    "icarr": 0.0,
    "seats": 0,
    "totalCarr": 72000.0,
    "currentSeats": 150
  },
  {
    "account": "Renewal [2026] - Ward Law Group, PL-",
    "owner": "Victor",
    "region": "AMER",
    "segment": "Renewal",
    "quarter": "Q2 2026",
    "month": "Apr",
    "closeDate": "2026-04-16",
    "status": "close-won",
    "closeLostReason": "",
    "closeLostNote": "",
    "closedWonNote": "Expanded renewal (160+55=215). The renewal discussion centered on aligning the contract with the customer?s actual usage and future growth while addressing their cost concerns. There was initial confusion around the current seat count and sensitivity to pricing, with a clear objective to reduce the cost per user. At the same time, the customer highlighted strong adoption across the organization, an AI-first strategy, and expectations to continue scaling both in users and API usage. To address this, different options were explored to balance seat volume and pricing, ensuring the agreement remained cost-effective while supporting their anticipated growth. Flexibility around true-ups and the credit system helped mitigate concerns about overcommitting, while the option of a separate API commitment was introduced for future needs without adding immediate complexity. By reinforcing the benefits of the credit system, the flexibility of true-ups, and the importance of aligning the contract with their expected growth, I guided the conversation toward a sustainable middle ground. This ultimately resulted in securing an increase from 160 to 215 seats at $35 per user per month, achieving both expansion and timely agreement while maintaining deal integrity.",
    "trendTags": [],
    "icarr": 13500.0,
    "seats": 55,
    "totalCarr": 76800.0,
    "currentSeats": 215
  },
  {
    "account": "Renewal [2026] - AlloSource-ChatGPT Enterprise",
    "owner": "Lakshay",
    "region": "AMER",
    "segment": "Renewal",
    "quarter": "Q2 2026",
    "month": "Apr",
    "closeDate": "2026-04-17",
    "status": "close-won",
    "closeLostReason": "",
    "closeLostNote": "",
    "closedWonNote": "CW (128->130), Non Profit pricing, customer sees the usage across the org to be at the current level in future",
    "trendTags": [],
    "icarr": -30480.0,
    "seats": 2,
    "totalCarr": 46080.0,
    "currentSeats": 130
  },
  {
    "account": "Renewal [2026] - Exostar-ChatGPT Enterprise",
    "owner": "Chantal",
    "region": "AMER",
    "segment": "Renewal",
    "quarter": "Q2 2026",
    "month": "Apr",
    "closeDate": "2026-04-17",
    "status": "close-won",
    "closeLostReason": "",
    "closeLostNote": "",
    "closedWonNote": "Contraction Renewal - 181 seats -> 75 seats. Currently has 75 activated seats. \"We're shifting some of our development users to a different toolset that's better aligned with their technical workflows. This is driving the reduction in seats rather than any decrease in headcount or overall AI usage. The remaining seats reflect our active ChatGPT users, and we want to make sure the renewal is sized accurately around that group going forward.\"",
    "trendTags": [
      "right-sizing"
    ],
    "icarr": -50880.0,
    "seats": -106,
    "totalCarr": 36000.0,
    "currentSeats": 75
  },
  {
    "account": "Renewal [2026] - Pensjonskassen for helseforetakene i hovedstadsomr\u00e5det (PKH)-",
    "owner": "Nicolas",
    "region": "EMEA",
    "segment": "Renewal",
    "quarter": "Q2 2026",
    "month": "Apr",
    "closeDate": "2026-04-17",
    "status": "close-won",
    "closeLostReason": "",
    "closeLostNote": "",
    "closedWonNote": "Renewal confirmed flat at 26 seats. Customer reviewed internal needs and confirmed no material expansion, with only a possible increase to 27 users over the coming year. Contractual terms remained unchanged, draft OF was approved, and signature was routed to the CEO, Mariann S. Bendriss.",
    "trendTags": [],
    "icarr": 0.0,
    "seats": 0,
    "totalCarr": 10296.0,
    "currentSeats": 26
  },
  {
    "account": "Renewal [2026] - Allen & Company-",
    "owner": "Chantal",
    "region": "AMER",
    "segment": "Renewal",
    "quarter": "Q2 2026",
    "month": "Apr",
    "closeDate": "2026-04-20",
    "status": "close-won",
    "closeLostReason": "",
    "closeLostNote": "",
    "closedWonNote": "Expansion Renewal - 84 seats -> 92 seats. Wanted to renew with activated seat count to continue usage for all current users.",
    "trendTags": [],
    "icarr": 3840.0,
    "seats": 8,
    "totalCarr": 44160.0,
    "currentSeats": 92
  },
  {
    "account": "Renewal [2026] - Ampsight, Inc. (ChatGPT 40)-",
    "owner": "Lori",
    "region": "AMER",
    "segment": "Renewal",
    "quarter": "Q2 2026",
    "month": "Apr",
    "closeDate": "2026-04-20",
    "status": "close-lost",
    "closeLostReason": "Self Service fits needs",
    "closeLostNote": "They have the need for only 2 seats. - Over Purchased last term.",
    "closedWonNote": "",
    "trendTags": [
      "budget-pricing"
    ],
    "icarr": -24480.0,
    "seats": -51,
    "totalCarr": 24480.0,
    "currentSeats": 51
  },
  {
    "account": "Renewal [2026] - Best in Parking AG-",
    "owner": "Ebel",
    "region": "EMEA",
    "segment": "Renewal",
    "quarter": "Q2 2026",
    "month": "Apr",
    "closeDate": "2026-04-20",
    "status": "close-won",
    "closeLostReason": "",
    "closeLostNote": "",
    "closedWonNote": "Flat renewal: 50 They declare the have an internal policy at Group level where specify not more the 50 seats can be approved for the company branch.",
    "trendTags": [],
    "icarr": -4200.0,
    "seats": 0,
    "totalCarr": 24000.0,
    "currentSeats": 50
  },
  {
    "account": "Renewal [2026] - ECE Real Estate Partners GmbH-",
    "owner": "Victor",
    "region": "EMEA",
    "segment": "Renewal",
    "quarter": "Q2 2026",
    "month": "Apr",
    "closeDate": "2026-04-20",
    "status": "close-won",
    "closeLostReason": "",
    "closeLostNote": "",
    "closedWonNote": "Flat renewal (50). The customers had doubts about the credit system, being afraid of having overages, but beyond that they are satisfied with the product and want to use it at the same capability.",
    "trendTags": [],
    "icarr": 0.0,
    "seats": 0,
    "totalCarr": 24000.0,
    "currentSeats": 50
  },
  {
    "account": "Renewal [2026] - GS1 US-ChatGPT Enterprise",
    "owner": "Lori",
    "region": "AMER",
    "segment": "Renewal",
    "quarter": "Q2 2026",
    "month": "Apr",
    "closeDate": "2026-04-20",
    "status": "close-lost",
    "closeLostReason": "Timing",
    "closeLostNote": "They asked for a month extension because they believed their renewal ended in May. They said they will reach out when they are ready but agree to churn for now.",
    "closedWonNote": "",
    "trendTags": [],
    "icarr": -12000.0,
    "seats": -25,
    "totalCarr": 12000.0,
    "currentSeats": 25
  },
  {
    "account": "Renewal [2026] - GiveDirectly-",
    "owner": "Chantal",
    "region": "AMER",
    "segment": "Renewal",
    "quarter": "Q2 2026",
    "month": "Apr",
    "closeDate": "2026-04-20",
    "status": "close-won",
    "closeLostReason": "",
    "closeLostNote": "",
    "closedWonNote": "Expansion Renewal - 166 seats -> 178 seats. Wanted to renew with current activated users.",
    "trendTags": [],
    "icarr": -38400.0,
    "seats": 12,
    "totalCarr": 21360.0,
    "currentSeats": 178
  },
  {
    "account": "Renewal [2026] - Merchant Capital LLC-ChatGPT Enterprise",
    "owner": "Lakshay",
    "region": "AMER",
    "segment": "Renewal",
    "quarter": "Q2 2026",
    "month": "Apr",
    "closeDate": "2026-04-20",
    "status": "close-won",
    "closeLostReason": "",
    "closeLostNote": "",
    "closedWonNote": "CW 50-> 25 ( Usage reduction in their workflows, and asked for a greater discount on the current number of seats on the platform for renewal )",
    "trendTags": [
      "right-sizing",
      "budget-pricing"
    ],
    "icarr": -12000.0,
    "seats": -25,
    "totalCarr": 24000.0,
    "currentSeats": 25
  },
  {
    "account": "Renewal [2026] - Odyssey Investment Partners-ChatGPT Enterprise",
    "owner": "Aditya",
    "region": "AMER",
    "segment": "Renewal",
    "quarter": "Q2 2026",
    "month": "Apr",
    "closeDate": "2026-04-20",
    "status": "close-won",
    "closeLostReason": "",
    "closeLostNote": "",
    "closedWonNote": "I had started coordinating with Rachel, she mentioned they had an event and would share the final numbers after it was done. But I never heard back from her. Then, with 6 days left, Vivian reached out and asked me to keep the number of seats the same, so I went ahead and did that. CW 50 users (flat)",
    "trendTags": [],
    "icarr": 0.0,
    "seats": 0,
    "totalCarr": 24000.0,
    "currentSeats": 50
  },
  {
    "account": "Renewal [2026] - AAA Life - ChatGPT Enterprise",
    "owner": "Tyler",
    "region": "AMER",
    "segment": "Renewal",
    "quarter": "Q2 2026",
    "month": "Apr",
    "closeDate": "2026-04-21",
    "status": "close-won",
    "closeLostReason": "",
    "closeLostNote": "",
    "closedWonNote": "Expansion (150 seats entitled -> 200 seats)",
    "trendTags": [],
    "icarr": 24000.0,
    "seats": 50,
    "totalCarr": 72000.0,
    "currentSeats": 200
  },
  {
    "account": "Renewal [2026] - Bernhard Capital Partners-ChatGPT Ent",
    "owner": "Ashana",
    "region": "AMER",
    "segment": "Renewal",
    "quarter": "Q2 2026",
    "month": "Apr",
    "closeDate": "2026-04-21",
    "status": "close-won",
    "closeLostReason": "",
    "closeLostNote": "",
    "closedWonNote": "Contraction (50 seats entitled -> 25 seats). Customer wanted to renew with only 12 users as they they are now using Claude. I recommended downgrading to Business and then he came back saying he will renew with the minimum. The customer said: \"The primary reason for the shift is tool integration, specifically with Excel and Powerpoint. We have tried many llm integrations and Claude is far and away the best. The ux has yielded very fast adoption. Model performance is probably not a factor in so much as it has been turned for these use cases and ux integration. Our firm is slightly price agnostic at this scale but we will optimize if there is zero use of a service!\"",
    "trendTags": [
      "right-sizing",
      "competitive-shift",
      "budget-pricing"
    ],
    "icarr": -12000.0,
    "seats": -25,
    "totalCarr": 24000.0,
    "currentSeats": 25
  },
  {
    "account": "Renewal [2026] - DFJ Growth Management LLC-ChatGPT Enterprise",
    "owner": "Aditya",
    "region": "AMER",
    "segment": "Renewal",
    "quarter": "Q2 2026",
    "month": "Apr",
    "closeDate": "2026-04-21",
    "status": "close-won",
    "closeLostReason": "",
    "closeLostNote": "",
    "closedWonNote": "After multiple follow-ups, Gil shared the number of seats they wanted to renew. He also requested to remove auto-renewal, which I processed accordingly. Three days before the contract expiration, he went ahead and signed the renewal. CW (25->25) Flat",
    "trendTags": [],
    "icarr": 0.0,
    "seats": 0,
    "totalCarr": 12000.0,
    "currentSeats": 25
  },
  {
    "account": "Renewal [2026] - Emerson Collective, LLC - ChatGPT Enterprise",
    "owner": "Lori",
    "region": "AMER",
    "segment": "Renewal",
    "quarter": "Q2 2026",
    "month": "Apr",
    "closeDate": "2026-04-21",
    "status": "close-won",
    "closeLostReason": "",
    "closeLostNote": "",
    "closedWonNote": "Flat Renewal - 209 seats -> 209 seats -> No room for expansion at this time.",
    "trendTags": [],
    "icarr": -50160.0,
    "seats": 0,
    "totalCarr": 75240.0,
    "currentSeats": 209
  },
  {
    "account": "Renewal [2026] - Ilex Capital-",
    "owner": "Ashana",
    "region": "EMEA",
    "segment": "Renewal",
    "quarter": "Q2 2026",
    "month": "Apr",
    "closeDate": "2026-04-21",
    "status": "close-won",
    "closeLostReason": "",
    "closeLostNote": "",
    "closedWonNote": "CW Expansion (25 seats entitled -> 30 seats) Customer said: \"We currently have 27 active users and I expect this to go up to 30 during the year. At peak adoption, I don?t expect more than 32-34 based on the projected headcount but this might change.\"",
    "trendTags": [],
    "icarr": 2400.0,
    "seats": 5,
    "totalCarr": 12000.0,
    "currentSeats": 30
  },
  {
    "account": "Renewal [2026] - John D. and Catherine T. MacArthur Foundation-ChatGPT Enterprise",
    "owner": "Lori",
    "region": "AMER",
    "segment": "Renewal",
    "quarter": "Q2 2026",
    "month": "Apr",
    "closeDate": "2026-04-21",
    "status": "close-won",
    "closeLostReason": "",
    "closeLostNote": "",
    "closedWonNote": "Expansion - 157 seats -> 180 seats -> Room for expansion and happy with pricing.",
    "trendTags": [],
    "icarr": -34920.0,
    "seats": 23,
    "totalCarr": 56520.0,
    "currentSeats": 180
  },
  {
    "account": "Renewal [2026] - Piping Rock Health Products, Inc",
    "owner": "Chantal",
    "region": "AMER",
    "segment": "Renewal",
    "quarter": "Q2 2026",
    "month": "Apr",
    "closeDate": "2026-04-21",
    "status": "close-won",
    "closeLostReason": "",
    "closeLostNote": "",
    "closedWonNote": "Contraction Renewal - 364 seats -> 350 seats. Only wanted to renew based on current usage, MAU is 338. Was initially planning on only renewing with 100 seats.",
    "trendTags": [
      "right-sizing"
    ],
    "icarr": -6720.0,
    "seats": -14,
    "totalCarr": 168000.0,
    "currentSeats": 350
  },
  {
    "account": "Renewal [2026] - interos.ai-",
    "owner": "Ashana",
    "region": "AMER",
    "segment": "Renewal",
    "quarter": "Q2 2026",
    "month": "Apr",
    "closeDate": "2026-04-21",
    "status": "close-won",
    "closeLostReason": "",
    "closeLostNote": "",
    "closedWonNote": "Contraction (84 entitled seats -> 60 seats) Customer's reason for reducing seats \"The seat reduction is primarily due to organizational changes/departing employees\"",
    "trendTags": [
      "right-sizing"
    ],
    "icarr": -11520.0,
    "seats": -24,
    "totalCarr": 40320.0,
    "currentSeats": 60
  },
  {
    "account": "Renewal [2026] - Bezos Earth Fund - ChatGPT Enterprise (NPF)",
    "owner": "Aditya",
    "region": "AMER",
    "segment": "Renewal",
    "quarter": "Q2 2026",
    "month": "Apr",
    "closeDate": "2026-04-22",
    "status": "close-won",
    "closeLostReason": "",
    "closeLostNote": "",
    "closedWonNote": "I initially reached out to Jose (primary contact), who directed me to Kristen, but she never responded. With ~15 days remaining, I looped in IT Services (Michelle ? itservices@bezosearthfund.org). She responded and provided the necessary contract details. After that, it took about 2 days for them to review and sign the agreement. They ultimately signed 8 days after the contract had expired. CW (50->60)",
    "trendTags": [],
    "icarr": -10800.0,
    "seats": 10,
    "totalCarr": 7200.0,
    "currentSeats": 60
  },
  {
    "account": "Renewal [2026] - FCP- ChatGPT Enterprise",
    "owner": "Lori",
    "region": "AMER",
    "segment": "Renewal",
    "quarter": "Q2 2026",
    "month": "Apr",
    "closeDate": "2026-04-22",
    "status": "close-lost",
    "closeLostReason": "Did not recognize full value",
    "closeLostNote": "They will not answer my emails or calls now that they have told us they want to churn.",
    "closedWonNote": "",
    "trendTags": [],
    "icarr": -12480.0,
    "seats": -26,
    "totalCarr": 12480.0,
    "currentSeats": 26
  },
  {
    "account": "Renewal [2026] - Mutuelle Pr\u00e9vifrance-",
    "owner": "Nicolas",
    "region": "EMEA",
    "segment": "Renewal",
    "quarter": "Q2 2026",
    "month": "Apr",
    "closeDate": "2026-04-22",
    "status": "close-won",
    "closeLostReason": "",
    "closeLostNote": "",
    "closedWonNote": "Renewal: Flat at 25 seats for upcoming term, despite broader org size of ~600 employees. Reason: customer reviewed current needs and wants to maintain the same scope only, stating ChatGPT is used for specific needs and they are not looking to expand at this stage. Value/usage signal: continued paid usage for a defined subset of users; customer explicitly declined to share more detail on internal use cases or other solutions in use for now, but said they can revisit later if needs evolve.",
    "trendTags": [],
    "icarr": 0.0,
    "seats": 0,
    "totalCarr": 9900.0,
    "currentSeats": 25
  },
  {
    "account": "Renewal [2026] - Pacvue - ChatGPT Enterprise",
    "owner": "Ashana",
    "region": "AMER",
    "segment": "Renewal",
    "quarter": "Q2 2026",
    "month": "Apr",
    "closeDate": "2026-04-22",
    "status": "close-won",
    "closeLostReason": "",
    "closeLostNote": "",
    "closedWonNote": "Contraction (629 entitled seats -> 100) Customer's reason \"We are reducing our user count to only those employees who have actively used/created in OpenAI. As you know the landscape of AI is rapidly changing and we find that Claude is more useful for our base at the moment.\"",
    "trendTags": [
      "right-sizing",
      "competitive-shift"
    ],
    "icarr": -178440.0,
    "seats": -529,
    "totalCarr": 226440.0,
    "currentSeats": 100
  },
  {
    "account": "Renewal [2026] - ?????? (IGPI) - Renewal",
    "owner": "Ebel",
    "region": "APAC",
    "segment": "Renewal",
    "quarter": "Q2 2026",
    "month": "Apr",
    "closeDate": "2026-04-23",
    "status": "close-won",
    "closeLostReason": "",
    "closeLostNote": "",
    "closedWonNote": "Flat renewal: 179 seats",
    "trendTags": [],
    "icarr": 0.0,
    "seats": 0,
    "totalCarr": 85920.0,
    "currentSeats": 179
  },
  {
    "account": "Renewal [2026] - Charles Pankow Builders, LTD- ChatGPT Enterprise Land",
    "owner": "Lakshay",
    "region": "AMER",
    "segment": "Renewal",
    "quarter": "Q2 2026",
    "month": "Apr",
    "closeDate": "2026-04-23",
    "status": "close-lost",
    "closeLostReason": "Competitor",
    "closeLostNote": "Customer has decided to move to an aggregate service that allows access to more LLMs",
    "closedWonNote": "",
    "trendTags": [
      "competitive-shift"
    ],
    "icarr": -41760.0,
    "seats": -87,
    "totalCarr": 41760.0,
    "currentSeats": 87
  },
  {
    "account": "Renewal [2026] - LOVOO- ChatGPT Enterprise",
    "owner": "Victor",
    "region": "EMEA",
    "segment": "Renewal",
    "quarter": "Q2 2026",
    "month": "Apr",
    "closeDate": "2026-04-23",
    "status": "close-won",
    "closeLostReason": "",
    "closeLostNote": "",
    "closedWonNote": "Contracted renewal (265-55=210). The customer wanted to reduce the number of seats after a proof of concept.",
    "trendTags": [
      "right-sizing"
    ],
    "icarr": -26400.0,
    "seats": -55,
    "totalCarr": 127200.0,
    "currentSeats": 210
  },
  {
    "account": "Renewal [2026] - Landratsamt Regensburg-",
    "owner": "Ebel",
    "region": "EMEA",
    "segment": "Renewal",
    "quarter": "Q2 2026",
    "month": "Apr",
    "closeDate": "2026-04-23",
    "status": "close-won",
    "closeLostReason": "",
    "closeLostNote": "",
    "closedWonNote": "Expanded renewal: 104->120 seats",
    "trendTags": [],
    "icarr": -2400.0,
    "seats": 16,
    "totalCarr": 49920.0,
    "currentSeats": 120
  },
  {
    "account": "Renewal [2026] - Lansigt-Chat",
    "owner": "Ebel",
    "region": "EMEA",
    "segment": "Renewal",
    "quarter": "Q2 2026",
    "month": "Apr",
    "closeDate": "2026-04-23",
    "status": "close-won",
    "closeLostReason": "",
    "closeLostNote": "",
    "closedWonNote": "Expanded (early) renewal 25->35 seats",
    "trendTags": [],
    "icarr": 4800.0,
    "seats": 10,
    "totalCarr": 12000.0,
    "currentSeats": 35
  },
  {
    "account": "Renewal [2026] - Pearl Meyer - ChatGPT Enterprise",
    "owner": "Lakshay",
    "region": "AMER",
    "segment": "Renewal",
    "quarter": "Q2 2026",
    "month": "Apr",
    "closeDate": "2026-04-23",
    "status": "close-won",
    "closeLostReason": "",
    "closeLostNote": "",
    "closedWonNote": "CW with adding seats ( 147-> 150)",
    "trendTags": [],
    "icarr": 1440.0,
    "seats": 3,
    "totalCarr": 70560.0,
    "currentSeats": 150
  },
  {
    "account": "Renewal [2026] - PubNub Inc.- ChatGPT Enterprise SMB",
    "owner": "Aditya",
    "region": "AMER",
    "segment": "Renewal",
    "quarter": "Q2 2026",
    "month": "Apr",
    "closeDate": "2026-04-23",
    "status": "close-won",
    "closeLostReason": "",
    "closeLostNote": "",
    "closedWonNote": "I was in touch with June regarding the seat reduction. She mentioned they are actively trying to reduce costs and identified that some seats were under-utilized, users either never logged in or used the platform very minimally. They want to align their spend with actual usage and only pay for actively used seats at this time. She also noted that they may add more seats in the future as the company grows. (They took long time to finalize the seat count). They also requested to remove the auto-renewal from the contract. CW (77->68)",
    "trendTags": [
      "right-sizing",
      "budget-pricing"
    ],
    "icarr": -4320.0,
    "seats": -9,
    "totalCarr": 36960.0,
    "currentSeats": 68
  },
  {
    "account": "Renewal [2026] - Auger Inc.-",
    "owner": "Chantal",
    "region": "AMER",
    "segment": "Renewal",
    "quarter": "Q2 2026",
    "month": "Apr",
    "closeDate": "2026-04-24",
    "status": "close-won",
    "closeLostReason": "",
    "closeLostNote": "",
    "closedWonNote": "Expansion Renewal - 149 seats -> 150 seats. Wanted to renew with current usage.",
    "trendTags": [],
    "icarr": 396.0,
    "seats": 1,
    "totalCarr": 59004.0,
    "currentSeats": 150
  },
  {
    "account": "Renewal [2026] - Discovery Education, Inc-",
    "owner": "Chantal",
    "region": "AMER",
    "segment": "Renewal",
    "quarter": "Q2 2026",
    "month": "Apr",
    "closeDate": "2026-04-24",
    "status": "close-won",
    "closeLostReason": "",
    "closeLostNote": "",
    "closedWonNote": "Contraction Renewal - 58 seats -> 50 seats. Only wanted to renew with current active users. \"our active user count has held steady around 50 for the past couple of months, and the remaining seats have gone unused.\"",
    "trendTags": [
      "right-sizing"
    ],
    "icarr": -2496.0,
    "seats": -8,
    "totalCarr": 15600.0,
    "currentSeats": 50
  },
  {
    "account": "Renewal [2026] - Northshore- ChatGPT Enterprise",
    "owner": "Chantal",
    "region": "AMER",
    "segment": "Renewal",
    "quarter": "Q2 2026",
    "month": "Apr",
    "closeDate": "2026-04-24",
    "status": "close-won",
    "closeLostReason": "",
    "closeLostNote": "",
    "closedWonNote": "Contraction Renewal - 47 seats -> 38 seats. Wanted to renew with then current activated seat count.",
    "trendTags": [
      "right-sizing"
    ],
    "icarr": -4320.0,
    "seats": -9,
    "totalCarr": 18240.0,
    "currentSeats": 38
  },
  {
    "account": "Renewal [2026] - PennantPark Investment Advisers, LLC-",
    "owner": "Ashana",
    "region": "AMER",
    "segment": "Renewal",
    "quarter": "Q2 2026",
    "month": "Apr",
    "closeDate": "2026-04-24",
    "status": "close-won",
    "closeLostReason": "",
    "closeLostNote": "",
    "closedWonNote": "Contraction (67 seats entitled -> 39 seats) Cx mentioned organizational changes and just focusing on highly engaged users. If additional licenses are needed throughout the term, they will go ahead and have them added.",
    "trendTags": [
      "right-sizing"
    ],
    "icarr": -13440.0,
    "seats": -28,
    "totalCarr": 32160.0,
    "currentSeats": 39
  },
  {
    "account": "Renewal [2026] - The Bazooka Companies, LLC-",
    "owner": "Aditya",
    "region": "AMER",
    "segment": "Renewal",
    "quarter": "Q2 2026",
    "month": "Apr",
    "closeDate": "2026-04-24",
    "status": "close-won",
    "closeLostReason": "",
    "closeLostNote": "",
    "closedWonNote": "They initially wanted to downgrade to the Business plan due to budget constraints and also wanted to ensure their workspace data could be retained. However, after discussions highlighting the importance and value of the product, they decided to proceed with renewal at the minimum headcount of 25 seats. CW (70->25)",
    "trendTags": [
      "budget-pricing"
    ],
    "icarr": -21600.0,
    "seats": -45,
    "totalCarr": 33600.0,
    "currentSeats": 25
  },
  {
    "account": "Renewal [2026] - Fractyl - OpenAI",
    "owner": "Tyler",
    "region": "AMER",
    "segment": "Renewal",
    "quarter": "Q2 2026",
    "month": "Apr",
    "closeDate": "2026-04-27",
    "status": "close-won",
    "closeLostReason": "",
    "closeLostNote": "",
    "closedWonNote": "87 seats > 50, they had budget cuts across all departments and they only had 45 activated seats.",
    "trendTags": [
      "budget-pricing"
    ],
    "icarr": -17760.0,
    "seats": -37,
    "totalCarr": 41760.0,
    "currentSeats": 50
  },
  {
    "account": "Renewal [2026] - Insurify, Inc-",
    "owner": "Ashana",
    "region": "AMER",
    "segment": "Renewal",
    "quarter": "Q2 2026",
    "month": "Apr",
    "closeDate": "2026-04-27",
    "status": "close-won",
    "closeLostReason": "",
    "closeLostNote": "",
    "closedWonNote": "Expansion (195 entitled seats -> 250 seats)",
    "trendTags": [],
    "icarr": 26400.0,
    "seats": 55,
    "totalCarr": 93600.0,
    "currentSeats": 250
  },
  {
    "account": "Renewal [2026] - Kwest Group - ChatGPT Enterprise",
    "owner": "Ashana",
    "region": "AMER",
    "segment": "Renewal",
    "quarter": "Q2 2026",
    "month": "Apr",
    "closeDate": "2026-04-27",
    "status": "close-won",
    "closeLostReason": "",
    "closeLostNote": "",
    "closedWonNote": "Expansion (83 entitled seats -> 90 seats)",
    "trendTags": [],
    "icarr": 3360.0,
    "seats": 7,
    "totalCarr": 39840.0,
    "currentSeats": 90
  },
  {
    "account": "Renewal [2026] - Oats Overnight, Inc.-ChatGPT Enterprise",
    "owner": "Ashana",
    "region": "AMER",
    "segment": "Renewal",
    "quarter": "Q2 2026",
    "month": "Apr",
    "closeDate": "2026-04-27",
    "status": "close-lost",
    "closeLostReason": "Did not recognize full value",
    "closeLostNote": "Customer said they wanted a a month-to-month arrangement on Enterprise, or a quarterly agreement. If not, they would fallback.",
    "closedWonNote": "",
    "trendTags": [
      "budget-pricing"
    ],
    "icarr": -75360.0,
    "seats": -157,
    "totalCarr": 75360.0,
    "currentSeats": 157
  },
  {
    "account": "Renewal [2026] - Rubicon Founders-ChatGPT Enterprise",
    "owner": "Lori",
    "region": "AMER",
    "segment": "Renewal",
    "quarter": "Q2 2026",
    "month": "Apr",
    "closeDate": "2026-04-27",
    "status": "close-won",
    "closeLostReason": "",
    "closeLostNote": "",
    "closedWonNote": "Contraction Renewal - 54 seats -> 50 seats -> over purchased seats. He said he never purchased 54 seats, however our system shows different under entitled seats. He wouldn't approve 54.",
    "trendTags": [
      "right-sizing"
    ],
    "icarr": -1920.0,
    "seats": -4,
    "totalCarr": 24000.0,
    "currentSeats": 50
  },
  {
    "account": "Renewal [2026] - ScaleOps Labs Ltd.- Velocity Land",
    "owner": "Ashana",
    "region": "EMEA",
    "segment": "Renewal",
    "quarter": "Q2 2026",
    "month": "Apr",
    "closeDate": "2026-04-27",
    "status": "close-won",
    "closeLostReason": "",
    "closeLostNote": "",
    "closedWonNote": "Expansion (106 entitled seats -> 114) Customer said \"We?ve been growing quite rapidly in terms of users, and our usage is expected to continue increasing\"",
    "trendTags": [],
    "icarr": 2472.0,
    "seats": 8,
    "totalCarr": 50880.0,
    "currentSeats": 114
  },
  {
    "account": "Renewal (2026) - Arquimea Group",
    "owner": "Nicolas",
    "region": "EMEA",
    "segment": "Renewal",
    "quarter": "Q2 2026",
    "month": "Apr",
    "closeDate": "2026-04-28",
    "status": "close-won",
    "closeLostReason": "",
    "closeLostNote": "",
    "closedWonNote": "Renewal expansion 343 to 372 seats. Customer initially asked to renew at 372 seats and confirmed future growth would be handled through incremental invoicing, as done this year.",
    "trendTags": [],
    "icarr": 130560.0,
    "seats": 29,
    "totalCarr": 164640.0,
    "currentSeats": 372
  },
  {
    "account": "Renewal [2026] - Beveridge & Diamond - ChatGPT Enterprise",
    "owner": "Tyler",
    "region": "AMER",
    "segment": "Renewal",
    "quarter": "Q2 2026",
    "month": "Apr",
    "closeDate": "2026-04-28",
    "status": "close-won",
    "closeLostReason": "",
    "closeLostNote": "",
    "closedWonNote": "200>230 seats",
    "trendTags": [],
    "icarr": 14400.0,
    "seats": 30,
    "totalCarr": 96000.0,
    "currentSeats": 230
  },
  {
    "account": "Renewal [2026] - Cincinnati Zoo-NPF Chat Land",
    "owner": "Chantal",
    "region": "AMER",
    "segment": "Renewal",
    "quarter": "Q2 2026",
    "month": "Apr",
    "closeDate": "2026-04-28",
    "status": "close-won",
    "closeLostReason": "",
    "closeLostNote": "",
    "closedWonNote": "Flat Renewal - 50 seats -> 50 seats. Only has 32 activated seats, \"We're slowly adopting some folks, and the current amount of licenses we hold will allow for some more expansion. That should keep us at 50 total licenses.\"",
    "trendTags": [],
    "icarr": -12000.0,
    "seats": 0,
    "totalCarr": 18000.0,
    "currentSeats": 50
  },
  {
    "account": "Renewal [2026] - Korea Investment Corporation - Chatgpt 150 license",
    "owner": "Ashana",
    "region": "APAC",
    "segment": "Renewal",
    "quarter": "Q2 2026",
    "month": "Apr",
    "closeDate": "2026-04-28",
    "status": "close-won",
    "closeLostReason": "",
    "closeLostNote": "",
    "closedWonNote": "Expansion (263 entitled seats -> 300 seats) Customer said: We recognize that driving meaningful expansion requires not only access, but also cultural and workflow changes.",
    "trendTags": [],
    "icarr": 17760.0,
    "seats": 37,
    "totalCarr": 126240.0,
    "currentSeats": 300
  },
  {
    "account": "Renewal [2026] - Ninedot Holdings, Inc. - Renewal",
    "owner": "Lakshay",
    "region": "AMER",
    "segment": "Renewal",
    "quarter": "Q2 2026",
    "month": "Apr",
    "closeDate": "2026-04-28",
    "status": "close-won",
    "closeLostReason": "",
    "closeLostNote": "",
    "closedWonNote": "CW with addition of seats ( 80->84)",
    "trendTags": [],
    "icarr": 1344.0,
    "seats": 4,
    "totalCarr": 26880.0,
    "currentSeats": 84
  },
  {
    "account": "Renewal [2026] - Once Upon a Farm-",
    "owner": "Aditya",
    "region": "AMER",
    "segment": "Renewal",
    "quarter": "Q2 2026",
    "month": "Apr",
    "closeDate": "2026-04-28",
    "status": "close-won",
    "closeLostReason": "",
    "closeLostNote": "",
    "closedWonNote": "We had a meeting where we discussed credits and different models. At the time, they had 81 activated users and were initially okay with renewing at that count. However, a few days later, they reached out requesting to revise the contract down to 65 users. When asked, they explained that they?re reducing access as some users are being removed and are not actively using the AI tool. CW (70->65)",
    "trendTags": [
      "right-sizing",
      "org-cleanup"
    ],
    "icarr": -2400.0,
    "seats": -5,
    "totalCarr": 33600.0,
    "currentSeats": 65
  },
  {
    "account": "Renewal [2026] - Stoneage Tools- ChatGPT Enterprise",
    "owner": "Lakshay",
    "region": "AMER",
    "segment": "Renewal",
    "quarter": "Q2 2026",
    "month": "Apr",
    "closeDate": "2026-04-28",
    "status": "close-won",
    "closeLostReason": "",
    "closeLostNote": "",
    "closedWonNote": "CW with adding seats ( 99->104)",
    "trendTags": [],
    "icarr": 2400.0,
    "seats": 5,
    "totalCarr": 49920.0,
    "currentSeats": 104
  },
  {
    "account": "Renewal [2026] - Van Eck - Early Renewal",
    "owner": "Lori",
    "region": "AMER",
    "segment": "Renewal",
    "quarter": "Q2 2026",
    "month": "Apr",
    "closeDate": "2026-04-28",
    "status": "close-won",
    "closeLostReason": "",
    "closeLostNote": "",
    "closedWonNote": "Contraction-> 474 -> 200 -> Notes from the customer: \"Primarily the growth that we had anticipated just hasn't materialized. when we signed at 400 seat, the grow trend was linear, then it flattened out. I can't comment on why the remaining users fail to materialize.\"",
    "trendTags": [
      "right-sizing"
    ],
    "icarr": -159960.0,
    "seats": -524,
    "totalCarr": 255960.0,
    "currentSeats": 200
  },
  {
    "account": "Trexquant - API + ChatGPT - Renewal (2026)",
    "owner": "Aditya",
    "region": "AMER",
    "segment": "Renewal",
    "quarter": "Q2 2026",
    "month": "Apr",
    "closeDate": "2026-04-28",
    "status": "close-won",
    "closeLostReason": "",
    "closeLostNote": "",
    "closedWonNote": "The renewal process was smooth overall, they clearly communicated the seat count and updated contract details upfront. The only issue raised was a support request to change the data retention setting to 90 days, which they mentioned hadn?t been completed. However, despite multiple follow-ups, we haven?t received a response from support on this. They also requested the contract to be executed via DocuSign. CW (183->200)",
    "trendTags": [],
    "icarr": 8160.0,
    "seats": 17,
    "totalCarr": 137840.0,
    "currentSeats": 200
  },
  {
    "account": "Renewal [2026] - BCS Automation Ltd.-ChatGPT Enterprise",
    "owner": "Ashana",
    "region": "AMER",
    "segment": "Renewal",
    "quarter": "Q2 2026",
    "month": "Apr",
    "closeDate": "2026-04-29",
    "status": "close-won",
    "closeLostReason": "",
    "closeLostNote": "",
    "closedWonNote": "Expansion (26 entitled seats -> 32 seats) Customer said: We are a growing company. I could see us having 50 users in two years time.",
    "trendTags": [],
    "icarr": 2880.0,
    "seats": 6,
    "totalCarr": 12480.0,
    "currentSeats": 32
  },
  {
    "account": "Renewal [2026] - ChatGPT Enterprise Colossal Biosciences seats",
    "owner": "Tyler",
    "region": "APAC",
    "segment": "Renewal",
    "quarter": "Q2 2026",
    "month": "Apr",
    "closeDate": "2026-04-29",
    "status": "close-won",
    "closeLostReason": "",
    "closeLostNote": "",
    "closedWonNote": "91>66",
    "trendTags": [],
    "icarr": -12000.0,
    "seats": -25,
    "totalCarr": 31680.0,
    "currentSeats": 66
  },
  {
    "account": "Renewal [2026] - Credigy - CBP 185 Seats",
    "owner": "Aditya",
    "region": "AMER",
    "segment": "Renewal",
    "quarter": "Q2 2026",
    "month": "Apr",
    "closeDate": "2026-04-29",
    "status": "close-won",
    "closeLostReason": "",
    "closeLostNote": "",
    "closedWonNote": "They clarified that the 342 activated users are not accurate. The higher number was due to a domain migration (crudity.net ? crudity.com), which caused temporary overlap in accounts. They also requested to remove Auto-Renewal.",
    "trendTags": [
      "org-cleanup"
    ],
    "icarr": -67620.0,
    "seats": -161,
    "totalCarr": 149940.0,
    "currentSeats": 196
  },
  {
    "account": "Renewal [2026] - Knight Foundation - ChatGPT Enterprise (NPF)",
    "owner": "Tyler",
    "region": "AMER",
    "segment": "Renewal",
    "quarter": "Q2 2026",
    "month": "Apr",
    "closeDate": "2026-04-29",
    "status": "close-won",
    "closeLostReason": "",
    "closeLostNote": "",
    "closedWonNote": "74 > 65",
    "trendTags": [],
    "icarr": -18840.0,
    "seats": -9,
    "totalCarr": 7800.0,
    "currentSeats": 65
  },
  {
    "account": "Renewal [2026] - Media Res Studio-",
    "owner": "Tyler",
    "region": "AMER",
    "segment": "Renewal",
    "quarter": "Q2 2026",
    "month": "Apr",
    "closeDate": "2026-04-29",
    "status": "close-lost",
    "closeLostReason": "Competitor",
    "closeLostNote": "They have fully transitioned to claude. When asked about the reason, this was their response: \"Our team just found the Claude outputs to be more comprehensive and formatting to be better than ChatGPT at this time",
    "closedWonNote": "",
    "trendTags": [
      "competitive-shift"
    ],
    "icarr": -18720.0,
    "seats": -39,
    "totalCarr": 18720.0,
    "currentSeats": 39
  },
  {
    "account": "Renewal [2026] - Prime Group Holding - ChatGPT Enterprise",
    "owner": "Aditya",
    "region": "AMER",
    "segment": "Renewal",
    "quarter": "Q2 2026",
    "month": "Apr",
    "closeDate": "2026-04-29",
    "status": "close-won",
    "closeLostReason": "",
    "closeLostNote": "",
    "closedWonNote": "Prospect mentioned-They?ve observed a shift in user behavior, with more employees moving toward alternative AI tools like Claude. This has led to internal concerns about the value of continuing ChatGPT Enterprise at the current pricing. They also requested a discount to justify the renewal, but we were unable to accommodate that from our side. They also requested if we can have month to month subscription. CW 50->50 (Flat)",
    "trendTags": [],
    "icarr": 0.0,
    "seats": 0,
    "totalCarr": 24000.0,
    "currentSeats": 50
  },
  {
    "account": "Renewal [2026] - Upland Capital Group-ChatGPT Velocity Land",
    "owner": "Tyler",
    "region": "AMER",
    "segment": "Renewal",
    "quarter": "Q2 2026",
    "month": "Apr",
    "closeDate": "2026-04-29",
    "status": "close-won",
    "closeLostReason": "",
    "closeLostNote": "",
    "closedWonNote": "72>75",
    "trendTags": [],
    "icarr": 8640.0,
    "seats": 18,
    "totalCarr": 36000.0,
    "currentSeats": 75
  },
  {
    "account": "Renewal [2026] - Basys - ChatGPT Enterprise",
    "owner": "Lakshay",
    "region": "AMER",
    "segment": "Renewal",
    "quarter": "Q2 2026",
    "month": "Apr",
    "closeDate": "2026-04-30",
    "status": "close-lost",
    "closeLostReason": "Self Service fits needs",
    "closeLostNote": "Downgraded to business for marketing team, major workforce moved to copilot",
    "closedWonNote": "",
    "trendTags": [
      "competitive-shift",
      "budget-pricing"
    ],
    "icarr": -72000.0,
    "seats": -150,
    "totalCarr": 72000.0,
    "currentSeats": 150
  },
  {
    "account": "Renewal [2026] - NANOREALITY GAMES S.L.-",
    "owner": "Victor",
    "region": "EMEA",
    "segment": "Renewal",
    "quarter": "Q2 2026",
    "month": "Apr",
    "closeDate": "2026-04-30",
    "status": "close-won",
    "closeLostReason": "",
    "closeLostNote": "",
    "closedWonNote": "Flat Renewal (25 seats). Customer is satisfied with the current adoption and plans to carry on using Enterprise for all the users they have.",
    "trendTags": [],
    "icarr": 0.0,
    "seats": 0,
    "totalCarr": 12000.0,
    "currentSeats": 25
  },
  {
    "account": "Renewal [2026] - Pinnacle Exhibits-",
    "owner": "Ashana",
    "region": "AMER",
    "segment": "Renewal",
    "quarter": "Q2 2026",
    "month": "Apr",
    "closeDate": "2026-04-30",
    "status": "close-won",
    "closeLostReason": "",
    "closeLostNote": "",
    "closedWonNote": "CW Flat (50) - I have had a hard tome reaching out to the customer. Still did not communicate with anyone however I prepared the Order Form and sent it through for a signature and they signed. They were 4 days away from their renewal date.",
    "trendTags": [],
    "icarr": 0.0,
    "seats": 0,
    "totalCarr": 24000.0,
    "currentSeats": 50
  },
  {
    "account": "Renewal [2026] - Raya - Chat",
    "owner": "Aditya",
    "region": "AMER",
    "segment": "Renewal",
    "quarter": "Q2 2026",
    "month": "Apr",
    "closeDate": "2026-04-30",
    "status": "close-won",
    "closeLostReason": "",
    "closeLostNote": "",
    "closedWonNote": "They confirmed they want to proceed with 85 seats and will remove any seats they no longer need directly from the portal. -> Adoption / training feedback: Their main challenge is with the engineering team staying up to date on best practices, including effective prompting, using skills efficiently, leveraging subagents, and MCP servers. They already have an internal marketplace and skills, but would be interested in learning what similar-sized companies are doing, especially around Codex usage and spend benchmarks. -> Expansion outlook: They are actively exploring ways to integrate LLMs more efficiently into their products. They were also excited about OpenAI availability on Bedrock and expect they may build with OpenAI models there in the near future. CW (110->85)",
    "trendTags": [
      "right-sizing"
    ],
    "icarr": -12000.0,
    "seats": -25,
    "totalCarr": 40800.0,
    "currentSeats": 85
  },
  {
    "account": "Renewal [2026] - Suveto-ChatGPT Enterprise",
    "owner": "Lori",
    "region": "AMER",
    "segment": "Renewal",
    "quarter": "Q2 2026",
    "month": "Apr",
    "closeDate": "2026-04-30",
    "status": "close-won",
    "closeLostReason": "",
    "closeLostNote": "",
    "closedWonNote": "Contraction -> 50 -> 35 -> They originally asked to downgrade to business because they felt they aren't using the features Enterprise offers and really just needed SSO. Through our discussions, they changed their mind and decided to stay but they said they really don't need all of the seats they did sign up originally. They only activated 33 seats the whole term.",
    "trendTags": [
      "right-sizing"
    ],
    "icarr": -7200.0,
    "seats": -15,
    "totalCarr": 16800.0,
    "currentSeats": 35
  },
  {
    "account": "Renewal [2026] - Warner Norcross + Judd - ChatGPT Enterprise",
    "owner": "Ashana",
    "region": "AMER",
    "segment": "Renewal",
    "quarter": "Q2 2026",
    "month": "Apr",
    "closeDate": "2026-04-30",
    "status": "close-won",
    "closeLostReason": "",
    "closeLostNote": "",
    "closedWonNote": "CW Flat (150) Customer said \"We just recently went through and cleaned up our user list ? we?re down to 145 active users now. Based on our analytics it looks like we?re at 113 WAU and 128 total active users, so the 150-seat level seems right for us right now.\"",
    "trendTags": [],
    "icarr": 0.0,
    "seats": 0,
    "totalCarr": 72000.0,
    "currentSeats": 150
  },
  {
    "account": "Renewal [2026] - Young Basile - ChatGPT Enterprise",
    "owner": "Lakshay",
    "region": "AMER",
    "segment": "Renewal",
    "quarter": "Q2 2026",
    "month": "Apr",
    "closeDate": "2026-04-30",
    "status": "close-lost",
    "closeLostReason": "Self Service fits needs",
    "closeLostNote": "Downgraded, as active users dropped to 14 and are looking for flexible payment terms instead of annual commitment",
    "closedWonNote": "",
    "trendTags": [
      "right-sizing",
      "budget-pricing"
    ],
    "icarr": -15840.0,
    "seats": -33,
    "totalCarr": 15840.0,
    "currentSeats": 33
  },
  {
    "account": "Renewal [2026] - broadhead - Renewal",
    "owner": "Tyler",
    "region": "AMER",
    "segment": "Renewal",
    "quarter": "Q2 2026",
    "month": "Apr",
    "closeDate": "2026-04-30",
    "status": "close-won",
    "closeLostReason": "",
    "closeLostNote": "",
    "closedWonNote": "150 flat",
    "trendTags": [],
    "icarr": 0.0,
    "seats": 0,
    "totalCarr": 72000.0,
    "currentSeats": 150
  },
  {
    "account": "Renewal [2026] - Adapt Forward, LLC-ChatGPT Enterprise",
    "owner": "Tyler",
    "region": "AMER",
    "segment": "Renewal",
    "quarter": "Q2 2026",
    "month": "May",
    "closeDate": "2026-05-01",
    "status": "close-lost",
    "closeLostReason": "Self Service fits needs",
    "closeLostNote": "Downgrading to Business due to only wanting 4 seats. Not losing to competitor, they have downsized staff massively",
    "closedWonNote": "",
    "trendTags": [
      "right-sizing",
      "competitive-shift",
      "budget-pricing"
    ],
    "icarr": -16800.0,
    "seats": -35,
    "totalCarr": 16800.0,
    "currentSeats": 35
  },
  {
    "account": "Renewal [2026] - Beach Camera - ChatGPT Enterprise",
    "owner": "Lori",
    "region": "AMER",
    "segment": "Renewal",
    "quarter": "Q2 2026",
    "month": "May",
    "closeDate": "2026-05-01",
    "status": "close-lost",
    "closeLostReason": "Self Service fits needs",
    "closeLostNote": "Preparing for a downgrade. He won't commit to $40. I did offer $39 and the $38. He said he will only commit if I can offer him $30 for 52 seats. Which we cannot. So he wants to downgrade to business.",
    "closedWonNote": "",
    "trendTags": [
      "budget-pricing"
    ],
    "icarr": -23520.0,
    "seats": -49,
    "totalCarr": 23520.0,
    "currentSeats": 49
  },
  {
    "account": "Renewal [2026] - Cabot Properties, Inc.-",
    "owner": "Victor",
    "region": "AMER",
    "segment": "Renewal",
    "quarter": "Q2 2026",
    "month": "May",
    "closeDate": "2026-05-01",
    "status": "close-won",
    "closeLostReason": "",
    "closeLostNote": "",
    "closedWonNote": "Expanded renewal (125+10=135). The customer needed 10 more seats before the endo of the contract to be pro-rated and added as soon as possible, and signed the early renewal for a expansion of 10 seats. They are increasing their adoption with deep research and Codex from Enterprise.",
    "trendTags": [],
    "icarr": 3960.0,
    "seats": 10,
    "totalCarr": 49500.0,
    "currentSeats": 135
  },
  {
    "account": "Renewal [2026] - Falfurrias Management Partners, LP-ChatGPT Enterprise",
    "owner": "Lakshay",
    "region": "AMER",
    "segment": "Renewal",
    "quarter": "Q2 2026",
    "month": "May",
    "closeDate": "2026-05-01",
    "status": "close-lost",
    "closeLostReason": "Competitor",
    "closeLostNote": "Moved to Competitor, citing an internal workflow-driven decision to move to another solution.",
    "closedWonNote": "",
    "trendTags": [
      "competitive-shift"
    ],
    "icarr": -23040.0,
    "seats": -48,
    "totalCarr": 23040.0,
    "currentSeats": 48
  },
  {
    "account": "Renewal [2026] - Fasanara Capital- ChatGPT Enterprise",
    "owner": "Nicolas",
    "region": "EMEA",
    "segment": "Renewal",
    "quarter": "Q2 2026",
    "month": "May",
    "closeDate": "2026-05-01",
    "status": "close-won",
    "closeLostReason": "",
    "closeLostNote": "",
    "closedWonNote": "Expansion renewal: Customer expanded from 50 to 130 ChatGPT Enterprise seats. Strong adoption signal, with customer stating they want to add the rest of the firm and may scale up to 200 users at peak adoption. Usage had been trending strongly, including increased Codex usage, which supported the expansion discussion. Final renewal structure: 130 seats, 500 credits/user, $34/user/month. Order form signed by Francesco Filia.",
    "trendTags": [],
    "icarr": 29040.0,
    "seats": 80,
    "totalCarr": 24000.0,
    "currentSeats": 130
  },
  {
    "account": "Renewal [2026] - Lumina Foundation for Education, Inc. - ChatGPT Enterprise",
    "owner": "Ashana",
    "region": "AMER",
    "segment": "Renewal",
    "quarter": "Q2 2026",
    "month": "May",
    "closeDate": "2026-05-01",
    "status": "close-won",
    "closeLostReason": "",
    "closeLostNote": "",
    "closedWonNote": "Flat renewal (55 Seats) Non-Profit.",
    "trendTags": [],
    "icarr": -13200.0,
    "seats": 0,
    "totalCarr": 19800.0,
    "currentSeats": 55
  },
  {
    "account": "Renewal [2026] - PLS Logistics - Renewal",
    "owner": "Victor",
    "region": "AMER",
    "segment": "Renewal",
    "quarter": "Q2 2026",
    "month": "May",
    "closeDate": "2026-05-01",
    "status": "close-won",
    "closeLostReason": "",
    "closeLostNote": "",
    "closedWonNote": "Contracted renewal (250-40=210). The customers bought 150 seats as they were told it was the minimal, but they have actually 110 active seats. They also have bought 20 seats of Claude from Anthropic, and they wanted to get ChatGPT Enterprise down to 80 seats. With the improvement in price offered I've managed to keep the 110 seats of ChatGPT Enterprise so they can improve their adoption instead of keep using Claude.",
    "trendTags": [
      "right-sizing",
      "competitive-shift",
      "budget-pricing"
    ],
    "icarr": -27120.0,
    "seats": -40,
    "totalCarr": 72000.0,
    "currentSeats": 110
  },
  {
    "account": "Renewal [2026] - RKE x Phenix Paving & Maintenance-ChatGPT 40 Seat Land",
    "owner": "Ashana",
    "region": "AMER",
    "segment": "Renewal",
    "quarter": "Q2 2026",
    "month": "May",
    "closeDate": "2026-05-01",
    "status": "close-lost",
    "closeLostReason": "Self Service fits needs",
    "closeLostNote": "They currently have 25 seats, with 14 activated in the workspace. However, these accounts were largely provisioned in anticipation of broader organizational adoption that ultimately did not materialize. While I?ve outlined the key benefits of Enterprise, they are only forecasting 3?5 active users for the upcoming term. The customer also emphasized that they are not looking to move away from OpenAI, but rather transition to a plan that better aligns with their current needs and usage.",
    "closedWonNote": "",
    "trendTags": [
      "right-sizing",
      "budget-pricing"
    ],
    "icarr": -12000.0,
    "seats": -25,
    "totalCarr": 12000.0,
    "currentSeats": 25
  },
  {
    "account": "Renewal [2026] - Renewal [May 2025] - Midland States Bank",
    "owner": "Lakshay",
    "region": "AMER",
    "segment": "Renewal",
    "quarter": "Q2 2026",
    "month": "May",
    "closeDate": "2026-05-01",
    "status": "close-won",
    "closeLostReason": "",
    "closeLostNote": "",
    "closedWonNote": "CW with expansion ( 255-> 307)",
    "trendTags": [],
    "icarr": 6540.0,
    "seats": 52,
    "totalCarr": 128940.0,
    "currentSeats": 307
  },
  {
    "account": "Renewal [2026] - SROA Capital",
    "owner": "Aditya",
    "region": "AMER",
    "segment": "Renewal",
    "quarter": "Q2 2026",
    "month": "May",
    "closeDate": "2026-05-01",
    "status": "close-won",
    "closeLostReason": "",
    "closeLostNote": "",
    "closedWonNote": "They delayed engagement on the renewal and only responded when 11 days were left before expiration. They currently have 95 entitled seats and chose to renew at the same seat count without any changes. CW 95 -> 95 (Flat)",
    "trendTags": [],
    "icarr": 0.0,
    "seats": 0,
    "totalCarr": 45600.0,
    "currentSeats": 95
  },
  {
    "account": "Renewal [2026] - Visiting Media LLC - ChatGPT Enterprise",
    "owner": "Lori",
    "region": "AMER",
    "segment": "Renewal",
    "quarter": "Q2 2026",
    "month": "May",
    "closeDate": "2026-05-01",
    "status": "close-won",
    "closeLostReason": "",
    "closeLostNote": "",
    "closedWonNote": "Over purchased last term - only 91 users out of 150 adopted it. They anticipate a few more users in the future so they agreed with 95 seats.",
    "trendTags": [],
    "icarr": -15840.0,
    "seats": -33,
    "totalCarr": 45600.0,
    "currentSeats": 95
  },
  {
    "account": "Renewal [2026] - Caldwell Watson Real Estate Group, Inc.-ChatGPT Enterprise",
    "owner": "Lori",
    "region": "AMER",
    "segment": "Renewal",
    "quarter": "Q2 2026",
    "month": "May",
    "closeDate": "2026-05-04",
    "status": "close-won",
    "closeLostReason": "",
    "closeLostNote": "",
    "closedWonNote": "Expansion -> 82 -> 87 -> Smooth renewal, they only want to pay for the exact amount of users that are using it and if they need to, they would rather true up later.",
    "trendTags": [],
    "icarr": 2400.0,
    "seats": 5,
    "totalCarr": 39360.0,
    "currentSeats": 87
  },
  {
    "account": "Renewal [2026] - Cormetech - ChatGPT Enterprise",
    "owner": "Lori",
    "region": "AMER",
    "segment": "Renewal",
    "quarter": "Q2 2026",
    "month": "May",
    "closeDate": "2026-05-04",
    "status": "close-won",
    "closeLostReason": "",
    "closeLostNote": "",
    "closedWonNote": "Expansion -> 42 -> 56 -> They anticipate small growth this year.",
    "trendTags": [],
    "icarr": 6720.0,
    "seats": 14,
    "totalCarr": 20160.0,
    "currentSeats": 56
  },
  {
    "account": "Renewal [2026] - Longitude Capital-",
    "owner": "Aditya",
    "region": "AMER",
    "segment": "Renewal",
    "quarter": "Q2 2026",
    "month": "May",
    "closeDate": "2026-05-04",
    "status": "close-won",
    "closeLostReason": "",
    "closeLostNote": "",
    "closedWonNote": "They are a ~30-employee organization currently using multiple AI tools, including Claude, Copilot, and BoxAI. They initially signed up for 100 ChatGPT Enterprise seats due to the minimum requirement at the time. They also already have Copilot and BoxAI deployed, which cover a significant portion of their needs and meet compliance requirements (tenant-isolated data). Because of this overlap, they find it difficult to justify a full-scale ChatGPT Enterprise deployment. CW (100 -> 30)",
    "trendTags": [
      "competitive-shift"
    ],
    "icarr": -27720.0,
    "seats": -70,
    "totalCarr": 39600.0,
    "currentSeats": 30
  },
  {
    "account": "Renewal [2026] - NCJUA-NCIUA- velocity Enterprise land",
    "owner": "Lori",
    "region": "AMER",
    "segment": "Renewal",
    "quarter": "Q2 2026",
    "month": "May",
    "closeDate": "2026-05-04",
    "status": "close-won",
    "closeLostReason": "",
    "closeLostNote": "",
    "closedWonNote": "Flat-> 52 -> 52-> They do not see any further expansion this term. Don't want to over purchase on seats they won't use.",
    "trendTags": [],
    "icarr": 0.0,
    "seats": 0,
    "totalCarr": 24960.0,
    "currentSeats": 52
  },
  {
    "account": "Renewal [2026] - Carmignac-",
    "owner": "Nicolas",
    "region": "EMEA",
    "segment": "Renewal",
    "quarter": "Q2 2026",
    "month": "May",
    "closeDate": "2026-05-05",
    "status": "close-won",
    "closeLostReason": "",
    "closeLostNote": "",
    "closedWonNote": "Renewal expanded from 280 to 295 seats. Customer initially projected 284 licenses with potential max of 320, then signed for 295 seats. Fully executed order form received.",
    "trendTags": [],
    "icarr": 46560.0,
    "seats": 15,
    "totalCarr": 134400.0,
    "currentSeats": 295
  },
  {
    "account": "Renewal [2026] - NEW BLACK - ChatGPT Enterprise",
    "owner": "Nicolas",
    "region": "EMEA",
    "segment": "Renewal",
    "quarter": "Q2 2026",
    "month": "May",
    "closeDate": "2026-05-05",
    "status": "close-won",
    "closeLostReason": "",
    "closeLostNote": "",
    "closedWonNote": "Contraction renewal from 100 to 15 users. Customer confirmed only ~10 users need to retain ChatGPT, primarily for voice/recording, specific GPTs, and research workflows. Broader org has shifted toward Claude, especially engineering due to Claude Code workflows and existing adoption. Customer still values OpenAI admin/governance experience and wants to keep an Enterprise footprint with SSO/admin controls to preserve optionality and keep the door open to scale back up if market/product fit shifts. 15-seat Enterprise exception approved by Gon\u00e7alo.",
    "trendTags": [
      "right-sizing",
      "competitive-shift"
    ],
    "icarr": -36480.0,
    "seats": -76,
    "totalCarr": 43680.0,
    "currentSeats": 15
  },
  {
    "account": "Renewal [2026] - Orkuveitan",
    "owner": "Nicolas",
    "region": "EMEA",
    "segment": "Renewal",
    "quarter": "Q2 2026",
    "month": "May",
    "closeDate": "2026-05-05",
    "status": "close-won",
    "closeLostReason": "",
    "closeLostNote": "",
    "closedWonNote": "Renewal contraction 309 -> 150 Customer initially intended to churn and move forward with another approach. After follow-up and discussion, renewal was saved with a contraction from 309 to 150 seats. Key renewal driver was moving into a new EU data residency workspace, with a manual migration and 2-week overlap period required because existing workspace data cannot be automatically transferred. Customer confirmed 150 licences for now, with ability to true up during the term.",
    "trendTags": [
      "right-sizing"
    ],
    "icarr": -76320.0,
    "seats": -159,
    "totalCarr": 72000.0,
    "currentSeats": 150
  },
  {
    "account": "Renewal [2026] - Three Crowns LLP - ChatGPT Ent",
    "owner": "Ebel",
    "region": "EMEA",
    "segment": "Renewal",
    "quarter": "Q2 2026",
    "month": "May",
    "closeDate": "2026-05-05",
    "status": "close-won",
    "closeLostReason": "",
    "closeLostNote": "",
    "closedWonNote": "Renewal expansion 165 -> 169",
    "trendTags": [],
    "icarr": 1920.0,
    "seats": 4,
    "totalCarr": 79200.0,
    "currentSeats": 169
  },
  {
    "account": "Renewal [2026] - Vix Technology UK Ltd-",
    "owner": "Victor",
    "region": "EMEA",
    "segment": "Renewal",
    "quarter": "Q2 2026",
    "month": "May",
    "closeDate": "2026-05-05",
    "status": "close-won",
    "closeLostReason": "",
    "closeLostNote": "",
    "closedWonNote": "Expanded renewal (93+58=151). The customer was experiencing important roadblocks due to the limits and 5 hours window in Codex. In the end we arrange a price to have an expansion that would give them enough pooled credits and did the early renewal to solve the problem as quick as possible.",
    "trendTags": [],
    "icarr": 18780.0,
    "seats": 58,
    "totalCarr": 63420.0,
    "currentSeats": 151
  }
];
